export const CONFIG = {
  // The current green diamond is expanded to roughly ten times its former
  // area. Most of that land is first-age wildwood: the two factions begin in
  // distant authored clearings and must deliberately cut new routes through
  // the forest instead of crossing one empty lawn.
  mapWidth: 560,
  mapHeight: 460,
  tileWidth: 52,
  tileHeight: 26,
  initialZoom: 0.16,
  minZoom: 0.035,
  maxZoom: 1.16,
  // Keep the first-age Crown Hall below the top HUD with a readable southern
  // approach and open construction space around the civic core.
  initialCameraWorld: { x: 78, z: 82 },
  // The normal slice uses a readable population ceiling. The 999-capacity
  // sandbox remains available through ?stress=1 for profiling and QA rather
  // than making every first match pay the cost of a stress test.
  sandboxMode: false,
  normalPopulationCapacity: 24,
  // Roads remain authored content for a later-age build feature. The opening
  // first-age map starts as an unroaded meadow so the settlement grows from
  // player decisions rather than presenting a finished route network.
  startingRoads: false,
  productionQueueLimit: 100,
  sandboxPopulationCapacity: 999,
  pathCacheLimit: 256,
  repathBudgetPerStep: 8,
  explorationCellSize: 16,
  explorationRadius: 24,
};

// The slice currently ships with one readable, forgiving enemy profile. It
// gives the player time to gather and build while preserving local awareness:
// Ashen Raiders still respond when the camp is attacked or a player unit gets
// too close, but the camp does not rush the Crown Hall at match start.
export const ENEMY_AI = {
  mode: 'easy',
  // The Ashen settlement grows through the same economy/construction loop as
  // the player. Long opening and follow-up windows keep that growth legible
  // without turning the first-age sandbox into a rush-defense puzzle.
  startingResources: { food: 320, wood: 430, stone: 190, gold: 45 },
  maxWorkers: 4,
  maxArmy: 7,
  maxTownStructures: 10,
  firstBuildDelay: 58,
  buildInterval: 48,
  workerTrainingDelay: 72,
  armyTrainingDelay: 44,
  firstRaidDelay: 190,
  followUpRaidDelay: 125,
  minRaidSize: 2,
  maxRaidSize: 4,
  awarenessRange: 5.2,
  defenseRange: 26,
  defenseDuration: 10,
};

export const LIGHTING = {
  primary: {
    label: 'upper-left / front',
    vector: { x: -0.48, y: -0.88 },
    shadowVector: { x: 0.48, y: 0.88 },
    warm: 'rgba(255, 226, 168, 0.055)',
    highlight: 'rgba(255, 239, 198, 0.03)',
  },
  ambient: {
    color: 'rgba(62, 91, 70, 0.042)',
    distantHaze: 'rgba(218, 231, 200, 0.035)',
  },
  mapEdgeShadow: 'rgba(16, 31, 27, 0.34)',
};

export const FACTION = {
  key: 'crownwardens',
  name: 'The Crownwardens',
  shortName: 'Crownwardens',
  color: '#86c4cf',
  darkColor: '#173844',
  gold: '#d7aa54',
};

export const RESOURCE_TYPES = {
  food: { label: 'Food', color: '#d76649', capacity: 9999, gatherAmount: 10, gatherTime: 1.05, interactionDistance: 1.55 },
  // Wildwood is a map-shaping resource rather than a handful of decorative
  // trees. Its bank must be able to hold a full woodland campaign; the former
  // 9,999 ceiling stopped crews before even one old-growth stand was cleared.
  wood: { label: 'Wood', color: '#b98147', capacity: 999999, gatherAmount: 12, gatherTime: 1.1, interactionDistance: 1.75 },
  stone: { label: 'Stone', color: '#9fa8ab', capacity: 9999, gatherAmount: 10, gatherTime: 1.2, interactionDistance: 1.7 },
  gold: { label: 'Gold', color: '#c6a15b', capacity: 9999, gatherAmount: 8, gatherTime: 1.3, interactionDistance: 1.72 },
};

// Resource size is data, not a one-off art trick. Every future material (for
// example metal) can opt into the same readable small/medium/large contract:
// larger silhouettes have a larger interaction footprint and a longer working
// life while bushes and other small food sources retain their normal scale.
export const RESOURCE_SIZE_TIERS = {
  small: { label: 'Small', renderScale: 1, capacityScale: 1, footprintScale: 1 },
  medium: { label: 'Medium', renderScale: 1.42, capacityScale: 2.2, footprintScale: 1.42 },
  large: { label: 'Large', renderScale: 2.05, capacityScale: 5, footprintScale: 2.05 },
  // Ancient forests remain available for legacy authored scenarios and QA.
  // Generated first-age Wildwood now uses independent small tree nodes so
  // each trunk can disappear cleanly when its own haul is exhausted.
  ancient: { label: 'Ancient', renderScale: 4.1, capacityScale: 12, footprintScale: 3.4 },
  // Wildwood is retained as a legacy tier for the six-stage atlas and older
  // QA fixtures. The live map no longer seeds this macro resource.
  wildwood: { label: 'Wildwood', renderScale: 5.8, capacityScale: 14, footprintScale: 9.5 },
};

export function resourceDepletionStage(node) {
  if (node?.type !== 'grove' || !(node.maxAmount > 0)) return 0;
  const stageCount = node.sizeTier === 'wildwood' ? 6 : 4;
  const ratio = Math.max(0, Math.min(1, node.amount / node.maxAmount));
  return Math.min(stageCount - 1, Math.floor((1 - ratio) * stageCount));
}

// Crownwardens and Ashen settlements draw from the same Hearthkin people.
// Faction colors and buildings stay distinct, but the shared worker contract
// keeps construction, defense, and recovery abilities consistent on both
// sides of the frontier.
const HEARTHKIN_WORKER_ABILITIES = Object.freeze({
  race: 'hearthkin',
  worker: true,
  canBuild: true,
  repairRate: 8,
  autoBuildRadius: 12,
  regroupAtTownCenter: true,
  canAttackUnits: true,
  canAttackBuildings: false,
  stunOnHit: Object.freeze({
    targetTrait: 'humanoid',
    duration: 5,
    immunityDuration: 20,
  }),
  lastLightWard: Object.freeze({
    duration: 60,
    curseDelay: 1.5,
    blastDuration: 0.9,
  }),
});

export const UNIT_TYPES = {
  villager: {
    ...HEARTHKIN_WORKER_ABILITIES,
    label: 'Hearthkin',
    asset: 'villager',
    renderSize: 88,
    // Builder behavior is data-driven so future worker or engineer units can
    // inherit construction, repair, and nearby auto-assist without adding
    // another unit-type check to the input or simulation layers.
    speed: 2.9,
    acceleration: 10.5,
    braking: 13.5,
    radius: 0.36,
    maxHp: 42,
    // Hearthkin can defend one another, but they remain workers rather than
    // substitute soldiers. An Ashen Raider has 72 HP, so 3.6 damage is an
    // exact twenty clean hits before armor gives way.
    attack: 3.6,
    range: 0.95,
    cooldown: 1.25,
    attackTiming: { anticipation: 0.2, contact: 0.46, recovery: 0.34 },
  },
  soldier: {
    label: 'Crown Guard',
    asset: 'soldier',
    renderSize: 120,
    speed: 2.45,
    radius: 0.43,
    maxHp: 85,
    attack: 14,
    range: 1.45,
    cooldown: 0.85,
    attackTiming: { anticipation: 0.24, contact: 0.44, recovery: 0.32 },
    combatAtlas: 'soldier',
    autoAggroRadius: 16,
  },
  raider: {
    label: 'Ashen Raider',
    asset: 'raider',
    renderSize: 120,
    speed: 2.25,
    radius: 0.44,
    maxHp: 72,
    attack: 9,
    // A Raider's committed axe blow is lethal to an unprotected worker. The
    // Villager's Last Light Ward intercepts that lethal result rather than
    // weakening the Marauder's threat against the settlement.
    attackVsVillager: 48,
    range: 1.25,
    cooldown: 1.05,
    attackTiming: { anticipation: 0.22, contact: 0.46, recovery: 0.32 },
    combatAtlas: 'raider',
    traits: ['humanoid'],
  },
  ashenForager: {
    ...HEARTHKIN_WORKER_ABILITIES,
    label: 'Hearthkin',
    asset: 'raider',
    renderSize: 104,
    speed: 2.75,
    acceleration: 10.2,
    braking: 13.2,
    radius: 0.36,
    maxHp: 38,
    attack: 2.4,
    range: 0.9,
    cooldown: 1.35,
    combatAtlas: 'ashenForagerMotion',
    traits: ['humanoid'],
  },
  ashenOutrider: {
    label: 'Ashen Outrider',
    asset: 'raider',
    renderSize: 184,
    speed: 3.75,
    acceleration: 11,
    braking: 14,
    radius: 0.7,
    maxHp: 58,
    attack: 9,
    range: 1.35,
    cooldown: 1.08,
    attackTiming: { anticipation: 0.22, contact: 0.43, recovery: 0.35 },
    combatAtlas: 'ashenOutriderMotion',
    traits: ['humanoid'],
  },
  thornSpear: {
    label: 'Thorn Spear',
    asset: 'raider',
    renderSize: 112,
    speed: 2.12,
    acceleration: 10.2,
    braking: 13,
    radius: 0.44,
    maxHp: 96,
    attack: 15,
    range: 1.6,
    cooldown: 1.08,
    attackTiming: { anticipation: 0.25, contact: 0.45, recovery: 0.34 },
    combatAtlas: 'thornSpearMotion',
    traits: ['humanoid'],
  },
  hearthLevy: {
    label: 'Hearth Levy',
    asset: 'raider',
    renderSize: 108,
    speed: 2.48,
    acceleration: 10.3,
    braking: 13.2,
    radius: 0.42,
    maxHp: 70,
    attack: 10,
    range: 1.22,
    cooldown: 0.98,
    attackTiming: { anticipation: 0.22, contact: 0.44, recovery: 0.34 },
    combatAtlas: 'hearthLevyMotion',
    traits: ['humanoid'],
  },
  hidewall: {
    label: 'Ashen Hidewall',
    asset: 'raider',
    renderSize: 112,
    speed: 2.05,
    acceleration: 10,
    braking: 13,
    radius: 0.44,
    maxHp: 110,
    attack: 11,
    range: 1.26,
    cooldown: 1.12,
    attackTiming: { anticipation: 0.24, contact: 0.46, recovery: 0.34 },
    combatAtlas: 'hidewallMotion',
    traits: ['humanoid'],
  },
  scout: {
    label: 'Crown Scout',
    // A mounted silhouette must read substantially larger than a foot unit.
    // The rider now matches Crown Guard human scale while the horse retains
    // its full mass, and the physical footprint follows the authored body.
    asset: 'soldier',
    renderSize: 190,
    speed: 4.15,
    acceleration: 11.5,
    braking: 14.5,
    radius: 0.72,
    maxHp: 62,
    attack: 10,
    range: 1.35,
    cooldown: 1.05,
    attackTiming: { anticipation: 0.2, contact: 0.42, recovery: 0.34 },
    combatAtlas: 'scout',
    autoAggroRadius: 18,
  },
  spearwarden: {
    label: 'Crown Spearwarden',
    // The authored atlas is the production render. Keep a Crown Guard image
    // as a safe loading fallback until the four-way Spearwarden sheets are
    // ready in the browser cache.
    asset: 'soldier',
    renderSize: 116,
    speed: 2.18,
    acceleration: 10.5,
    braking: 13.2,
    radius: 0.45,
    maxHp: 108,
    attack: 17,
    range: 1.62,
    cooldown: 1.02,
    attackTiming: { anticipation: 0.24, contact: 0.45, recovery: 0.33 },
    combatAtlas: 'spearwarden',
    autoAggroRadius: 16,
  },
  militia: {
    label: 'Crown Militia',
    // The Militia has its own lighter first-age silhouette and mace/shield
    // language. Keep the established unit fallback while the authored sheets
    // are loading so the queue never produces a blank entity.
    asset: 'soldier',
    renderSize: 112,
    speed: 2.55,
    acceleration: 10.5,
    braking: 13.5,
    radius: 0.42,
    maxHp: 78,
    attack: 11,
    range: 1.25,
    cooldown: 0.95,
    attackTiming: { anticipation: 0.22, contact: 0.44, recovery: 0.34 },
    combatAtlas: 'militia',
    autoAggroRadius: 14,
  },
  shieldbearer: {
    label: 'Crown Shieldbearer',
    asset: 'soldier',
    renderSize: 116,
    speed: 2.2,
    acceleration: 10.2,
    braking: 13.2,
    radius: 0.44,
    maxHp: 118,
    attack: 12,
    range: 1.28,
    cooldown: 1.08,
    attackTiming: { anticipation: 0.24, contact: 0.46, recovery: 0.34 },
    combatAtlas: 'shieldbearer',
    autoAggroRadius: 15,
  },
};

export const SPACING_ROLES = {
  villager: { personalSpace: 1.08, groupGap: 1.45 },
  soldier: { personalSpace: 1.28, groupGap: 1.72 },
  raider: { personalSpace: 1.32, groupGap: 1.78 },
  scout: { personalSpace: 1.82, groupGap: 2.34 },
  spearwarden: { personalSpace: 1.34, groupGap: 1.8 },
  militia: { personalSpace: 1.27, groupGap: 1.7 },
  shieldbearer: { personalSpace: 1.3, groupGap: 1.76 },
  ashenForager: { personalSpace: 1.08, groupGap: 1.45 },
  ashenOutrider: { personalSpace: 1.8, groupGap: 2.3 },
  thornSpear: { personalSpace: 1.34, groupGap: 1.8 },
  hearthLevy: { personalSpace: 1.27, groupGap: 1.7 },
  hidewall: { personalSpace: 1.3, groupGap: 1.76 },
};

export const PRODUCTION_TYPES = {
  villager: {
    label: 'Hearthkin',
    icon: 'icon-villager',
    building: 'townCenter',
    trainTime: 4,
    cost: { food: 50, wood: 0, stone: 0 },
  },
  soldier: {
    label: 'Crown Guard',
    icon: 'icon-soldier',
    building: 'barracks',
    trainTime: 6,
    // Gold earns its first clear strategic use through the existing military
    // loop. This remains a restrained equipment cost rather than a second
    // currency tree or a new unit roster.
    cost: { food: 40, wood: 15, stone: 0, gold: 10 },
  },
  scout: {
    label: 'Crown Scout',
    icon: 'icon-soldier',
    building: 'stable',
    trainTime: 8,
    cost: { food: 60, wood: 30, stone: 0, gold: 15 },
  },
  spearwarden: {
    label: 'Crown Spearwarden',
    icon: 'icon-soldier',
    building: 'barracks',
    trainTime: 8,
    cost: { food: 55, wood: 20, stone: 0, gold: 15 },
  },
  militia: {
    label: 'Crown Militia',
    icon: 'icon-soldier',
    building: 'barracks',
    trainTime: 5.5,
    cost: { food: 35, wood: 10, stone: 0, gold: 5 },
  },
  shieldbearer: {
    label: 'Crown Shieldbearer',
    icon: 'icon-soldier',
    building: 'barracks',
    trainTime: 7,
    cost: { food: 45, wood: 20, stone: 0, gold: 5 },
  },
  ashenForager: {
    label: 'Hearthkin',
    icon: 'icon-villager',
    building: 'ashenCamp',
    trainTime: 7,
    cost: { food: 45, wood: 0, stone: 0, gold: 0 },
  },
  raider: {
    label: 'Ashen Raider',
    icon: 'icon-soldier',
    building: 'reaverLodge',
    trainTime: 8,
    cost: { food: 45, wood: 15, stone: 0, gold: 5 },
  },
  ashenOutrider: {
    label: 'Ashen Outrider',
    icon: 'icon-soldier',
    building: 'beastCorral',
    trainTime: 10,
    cost: { food: 65, wood: 25, stone: 0, gold: 10 },
  },
  thornSpear: {
    label: 'Thorn Spear',
    icon: 'icon-soldier',
    building: 'reaverLodge',
    trainTime: 9,
    cost: { food: 55, wood: 20, stone: 0, gold: 10 },
  },
  hearthLevy: {
    label: 'Hearth Levy',
    icon: 'icon-soldier',
    building: 'reaverLodge',
    trainTime: 6,
    cost: { food: 35, wood: 10, stone: 0, gold: 0 },
  },
  hidewall: {
    label: 'Ashen Hidewall',
    icon: 'icon-soldier',
    building: 'reaverLodge',
    trainTime: 8,
    cost: { food: 45, wood: 20, stone: 0, gold: 5 },
  },
};

export const BUILDING_TYPES = {
  townCenter: {
    label: 'Crown Hall',
    function: 'Resource drop-off and settlement core',
    asset: 'townCenter',
    maxHp: 900,
    // The first-age Hall uses the Crown Barracks render scale as its shared
    // settlement reference. Human units keep their established scale;
    // gameplay bounds remain generous enough for the south stair approach and
    // future building.
    footprint: { width: 9, height: 8 },
    renderSize: 1000,
    // Building rasters use a near/front ground anchor. The physical base is
    // therefore both larger than the old placement tile and centered behind
    // that anchor in world space. Keeping this authored per structure makes
    // collision follow the actual courtyard instead of the image midpoint.
    collisionFootprint: { width: 17, height: 14 },
    collisionOffset: { x: -6.6, z: -6.6 },
    collisionClearance: 1.8,
    // This extra ring applies only to moving units. Keeping it separate from
    // collisionClearance prevents the larger no-entry boundary from changing
    // drop-off priority, placement spacing, or the authored building scale.
    unitExclusionPadding: 1.8,
    allowsUnitOcclusion: true,
    interactionSlots: 8,
    entrance: 'south',
    // The first-age Hall has a readable south stair run. Units may enter only
    // this corridor and stop on the top landing; the rest of the monument
    // remains a solid gameplay obstacle until a future interior system exists.
    stairAccess: {
      direction: 'south',
      width: 4.6,
      topOffset: 5.0,
      outerOffset: 9.0,
      stepCount: 8,
      visualRise: 8,
    },
    completed: true,
    storage: true,
    acceptsResources: ['food', 'wood', 'stone', 'gold'],
    production: true,
    productionTypes: ['villager'],
  },
  house: {
    label: 'Hearth House',
    function: 'Population housing',
    asset: 'house',
    maxHp: 260,
    footprint: { width: 4, height: 3 },
    renderSize: 350,
    collisionFootprint: { width: 5.4, height: 4.4 },
    collisionOffset: { x: -2.2, z: -2.2 },
    collisionClearance: 0.8,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 7.5,
    cost: { food: 0, wood: 55, stone: 0 },
    population: 4,
  },
  barracks: {
    label: 'Crown Barracks',
    function: 'Crown Guard production',
    asset: 'barracks',
    maxHp: 480,
    // The approved Barracks raster contains full-size practice dummies. At
    // this render width those dummies resolve to the same readable scale as
    // the live Marauder while the building remains a substantial military
    // landmark. Human units themselves are not rescaled.
    footprint: { width: 6, height: 5 },
    renderSize: 1000,
    collisionFootprint: { width: 15, height: 12.5 },
    collisionOffset: { x: -6.6, z: -6.6 },
    collisionClearance: 1.5,
    allowsUnitOcclusion: true,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 10,
    cost: { food: 0, wood: 90, stone: 40 },
    production: true,
    productionTypes: ['soldier', 'militia', 'shieldbearer', 'spearwarden'],
  },
  stable: {
    label: 'Crown Stable',
    function: 'Fast mounted scout production',
    asset: 'stable',
    maxHp: 460,
    footprint: { width: 5, height: 4 },
    renderSize: 660,
    collisionFootprint: { width: 10.5, height: 8.5 },
    collisionOffset: { x: -4.4, z: -4.4 },
    collisionClearance: 1.1,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 12,
    cost: { food: 0, wood: 120, stone: 30 },
    production: true,
    productionTypes: ['scout'],
  },
  granary: {
    label: 'First-age Granary',
    function: 'Food drop-off and grain support',
    asset: 'granary',
    maxHp: 350,
    footprint: { width: 4, height: 3 },
    renderSize: 420,
    collisionFootprint: { width: 6.5, height: 5.5 },
    collisionOffset: { x: -2.8, z: -2.8 },
    collisionClearance: 0.8,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 8,
    cost: { food: 0, wood: 70, stone: 10 },
    storage: true,
    acceptsResources: ['food'],
    autoWork: { resourceType: 'food', radius: 40 },
    gatherBonus: { resourceType: 'food', radius: 14, multiplier: 1.15 },
  },
  homestead: {
    label: 'First-age Homestead',
    function: 'Population housing',
    asset: 'homestead',
    maxHp: 300,
    footprint: { width: 4, height: 3 },
    renderSize: 430,
    collisionFootprint: { width: 6.5, height: 5.5 },
    collisionOffset: { x: -2.85, z: -2.85 },
    collisionClearance: 0.85,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 8,
    cost: { food: 0, wood: 80, stone: 10 },
    population: 6,
  },
  watchHut: {
    label: 'First-age Watch Hut',
    function: 'Settlement lookout and defensive landmark',
    asset: 'watchHut',
    maxHp: 300,
    footprint: { width: 3.5, height: 3.5 },
    renderSize: 410,
    collisionFootprint: { width: 5.5, height: 5 },
    collisionOffset: { x: -2.6, z: -2.6 },
    collisionClearance: 0.8,
    allowsUnitOcclusion: true,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 7,
    cost: { food: 0, wood: 65, stone: 15 },
    defense: {
      range: 18,
      damage: 8,
      cooldown: 1.45,
      projectileSpeed: 30,
      portRadius: 0.9,
    },
  },
  timberYard: {
    label: 'Timber Yard',
    function: 'Wood drop-off and nearby felling support',
    asset: 'timberYard',
    maxHp: 340,
    footprint: { width: 4, height: 3 },
    renderSize: 410,
    collisionFootprint: { width: 6.5, height: 5.5 },
    collisionOffset: { x: -2.75, z: -2.75 },
    collisionClearance: 0.8,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 7,
    cost: { food: 0, wood: 55, stone: 10 },
    storage: true,
    acceptsResources: ['wood'],
    autoWork: { resourceType: 'wood', radius: 40 },
    gatherBonus: { resourceType: 'wood', radius: 14, multiplier: 1.15 },
  },
  stonewrightYard: {
    label: 'Stonewright Yard',
    function: 'Stone drop-off and nearby shaping support',
    asset: 'stonewrightYard',
    maxHp: 360,
    footprint: { width: 4, height: 3 },
    renderSize: 410,
    collisionFootprint: { width: 6.5, height: 5.5 },
    collisionOffset: { x: -2.75, z: -2.75 },
    collisionClearance: 0.8,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 7,
    cost: { food: 0, wood: 45, stone: 25 },
    storage: true,
    acceptsResources: ['stone'],
    autoWork: { resourceType: 'stone', radius: 40 },
    gatherBonus: { resourceType: 'stone', radius: 15, multiplier: 1.15 },
  },
  oreWash: {
    label: 'Ore Wash',
    function: 'Gold drop-off and nearby ore-washing support',
    asset: 'oreWash',
    maxHp: 320,
    // This is a practical first-age work yard, not a civic landmark. Its
    // modest footprint and render width keep the Hall and Barracks dominant.
    footprint: { width: 4, height: 3 },
    renderSize: 380,
    collisionFootprint: { width: 6, height: 5 },
    collisionOffset: { x: -2.45, z: -2.45 },
    collisionClearance: 0.75,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 7,
    cost: { food: 0, wood: 60, stone: 20, gold: 0 },
    storage: true,
    acceptsResources: ['gold'],
    autoWork: { resourceType: 'gold', radius: 40 },
    // Nearby washing and sorting raises each completed Gold load from 8 to
    // 10. Multiple Ore Washes never stack; the simulation takes the strongest
    // single local bonus.
    gatherBonus: { resourceType: 'gold', radius: 16, multiplier: 1.25 },
  },
  lumberMill: {
    label: 'Lumber Mill',
    function: 'Wood drop-off',
    asset: 'lumberMill',
    maxHp: 340,
    footprint: { width: 4, height: 3 },
    renderSize: 260,
    collisionFootprint: { width: 4.5, height: 3.8 },
    collisionOffset: { x: -1.6, z: -1.6 },
    collisionClearance: 0.65,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 7,
    cost: { food: 0, wood: 45, stone: 10 },
    storage: true,
    acceptsResources: ['wood'],
    autoWork: { resourceType: 'wood', radius: 40 },
  },
  quarry: {
    label: 'Stone Quarry',
    function: 'Stone drop-off',
    asset: 'quarry',
    maxHp: 380,
    footprint: { width: 4, height: 3 },
    renderSize: 270,
    collisionFootprint: { width: 4.7, height: 4 },
    collisionOffset: { x: -1.65, z: -1.65 },
    collisionClearance: 0.65,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 7,
    cost: { food: 0, wood: 35, stone: 25 },
    storage: true,
    acceptsResources: ['stone'],
    autoWork: { resourceType: 'stone', radius: 40 },
  },
  grainMill: {
    label: 'Grain Mill',
    function: 'Food drop-off',
    asset: 'grainMill',
    maxHp: 360,
    footprint: { width: 4, height: 3 },
    renderSize: 275,
    collisionFootprint: { width: 4.7, height: 4 },
    collisionOffset: { x: -1.7, z: -1.7 },
    collisionClearance: 0.65,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 7,
    cost: { food: 0, wood: 50, stone: 10 },
    storage: true,
    acceptsResources: ['food'],
    autoWork: { resourceType: 'food', radius: 40 },
  },
  field: {
    label: 'Grain Field',
    function: 'One-farmer food plot',
    asset: 'field',
    maxHp: 150,
    // A field is a working plot, not a tiny decorative tile. Its footprint
    // is intentionally about four times the previous plot area so the crop
    // rows read as a meaningful part of the settlement at normal zoom.
    footprint: { width: 8, height: 6 },
    renderSize: 500,
    collisionClearance: 0.72,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 5,
    cost: { food: 0, wood: 25, stone: 0 },
    field: true,
    walkable: true,
  },
  road: {
    label: 'Packed Road',
    function: 'Fast, reliable settlement route',
    asset: 'road',
    maxHp: 80,
    footprint: { width: 2.6, height: 1.55 },
    renderSize: 118,
    collisionClearance: 0.05,
    interactionSlots: 4,
    entrance: 'south',
    buildTime: 1.8,
    cost: { food: 0, wood: 8, stone: 0 },
    walkable: true,
    road: true,
  },
  wall: {
    label: 'Palisade Wall',
    function: 'Defensive boundary',
    asset: 'wall',
    maxHp: 260,
    footprint: { width: 3, height: 1 },
    renderSize: 190,
    collisionClearance: 0.48,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 4,
    cost: { food: 0, wood: 20, stone: 10 },
    wall: true,
    wallSegmentSpan: 3,
  },
  gate: {
    label: 'Palisade Gate',
    function: 'Passable defensive entryway',
    asset: 'gate',
    maxHp: 300,
    footprint: { width: 3.2, height: 1.35 },
    renderSize: 250,
    collisionClearance: 0.48,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 5,
    cost: { food: 0, wood: 40, stone: 15 },
    gate: true,
    wallAttachment: true,
    walkable: true,
  },
  palisadeTower: {
    label: 'Palisade Tower',
    function: 'Reinforced wall hardpoint',
    asset: 'palisadeTower',
    maxHp: 480,
    footprint: { width: 3.6, height: 3.6 },
    renderSize: 300,
    collisionFootprint: { width: 4.2, height: 4.2 },
    // The tower artwork is centered on its ground socket. Keeping the
    // collision body centered prevents units from occupying the visible
    // tower while an invisible blocker sits down-left of it.
    collisionOffset: { x: 0, z: 0 },
    collisionClearance: 0.55,
    allowsUnitOcclusion: true,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 7,
    cost: { food: 0, wood: 85, stone: 20 },
    wallAttachment: true,
    defense: {
      range: 21,
      damage: 10,
      cooldown: 1.15,
      projectileSpeed: 34,
      portRadius: 1.25,
      ports: 4,
    },
  },
  storehouse: {
    label: 'Waystore',
    function: 'Resource drop-off',
    asset: 'storehouse',
    maxHp: 420,
    footprint: { width: 4, height: 3 },
    renderSize: 370,
    collisionFootprint: { width: 5.8, height: 4.8 },
    collisionOffset: { x: -2.25, z: -2.25 },
    collisionClearance: 0.8,
    interactionSlots: 8,
    entrance: 'south',
    completed: true,
    storage: true,
    acceptsResources: ['food', 'wood', 'stone', 'gold'],
  },
  ashenCamp: {
    label: 'Ashen Hearth',
    function: 'Enemy resource drop-off, worker lodge, and settlement core',
    asset: 'ashenCamp',
    maxHp: 760,
    footprint: { width: 8, height: 6 },
    renderSize: 620,
    collisionFootprint: { width: 11, height: 9 },
    collisionOffset: { x: -4.3, z: -4.3 },
    collisionClearance: 1.25,
    allowsUnitOcclusion: true,
    interactionSlots: 8,
    entrance: 'south',
    spawnDistance: 2,
    completed: true,
    enemyStructure: true,
    storage: true,
    acceptsResources: ['food', 'wood', 'stone', 'gold'],
    production: true,
    productionTypes: ['ashenForager'],
  },
  reaverLodge: {
    label: 'Reaver Lodge',
    function: 'Ashen infantry gathering hall',
    asset: 'reaverLodge',
    maxHp: 500,
    footprint: { width: 7, height: 5 },
    renderSize: 580,
    collisionFootprint: { width: 10, height: 8 },
    collisionOffset: { x: -4, z: -4 },
    collisionClearance: 1.05,
    allowsUnitOcclusion: true,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 12,
    cost: { food: 0, wood: 100, stone: 35, gold: 0 },
    enemyStructure: true,
    production: true,
    productionTypes: ['raider', 'hearthLevy', 'hidewall', 'thornSpear'],
  },
  beastCorral: {
    label: 'Beast Corral',
    function: 'Ashen mounted outrider training',
    asset: 'beastCorral',
    maxHp: 460,
    footprint: { width: 6, height: 5 },
    renderSize: 540,
    collisionFootprint: { width: 9, height: 7.5 },
    collisionOffset: { x: -3.6, z: -3.6 },
    collisionClearance: 1,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 13,
    cost: { food: 0, wood: 125, stone: 20, gold: 0 },
    enemyStructure: true,
    production: true,
    productionTypes: ['ashenOutrider'],
  },
  smokeGranary: {
    label: 'Smoke Granary',
    function: 'Ashen food drop-off and preserving shelter',
    asset: 'smokeGranary',
    maxHp: 330,
    footprint: { width: 4, height: 3 },
    renderSize: 330,
    collisionFootprint: { width: 5.7, height: 4.8 },
    collisionOffset: { x: -2.25, z: -2.25 },
    collisionClearance: 0.75,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 8,
    cost: { food: 0, wood: 65, stone: 10, gold: 0 },
    enemyStructure: true,
    storage: true,
    acceptsResources: ['food'],
    gatherBonus: { resourceType: 'food', radius: 14, multiplier: 1.12 },
  },
  hideHomestead: {
    label: 'Hide Homestead',
    function: 'Ashen population shelter',
    asset: 'hideHomestead',
    maxHp: 280,
    footprint: { width: 4, height: 3 },
    renderSize: 340,
    collisionFootprint: { width: 5.8, height: 4.9 },
    collisionOffset: { x: -2.3, z: -2.3 },
    collisionClearance: 0.75,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 8,
    cost: { food: 0, wood: 75, stone: 5, gold: 0 },
    population: 6,
    enemyStructure: true,
  },
  signalRoost: {
    label: 'Signal Roost',
    function: 'Ashen lookout and rally marker',
    asset: 'signalRoost',
    maxHp: 300,
    footprint: { width: 3.5, height: 3.5 },
    renderSize: 350,
    collisionFootprint: { width: 5.2, height: 5 },
    collisionOffset: { x: -2.1, z: -2.1 },
    collisionClearance: 0.75,
    allowsUnitOcclusion: true,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 8,
    cost: { food: 0, wood: 60, stone: 15, gold: 0 },
    enemyStructure: true,
  },
  ashenTimberRack: {
    label: 'Timber Rack',
    function: 'Ashen wood drop-off and felling support',
    asset: 'ashenTimberRack',
    maxHp: 320,
    footprint: { width: 4, height: 3 },
    renderSize: 320,
    collisionFootprint: { width: 5.6, height: 4.7 },
    collisionOffset: { x: -2.2, z: -2.2 },
    collisionClearance: 0.72,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 7,
    cost: { food: 0, wood: 50, stone: 5, gold: 0 },
    enemyStructure: true,
    storage: true,
    acceptsResources: ['wood'],
    gatherBonus: { resourceType: 'wood', radius: 14, multiplier: 1.12 },
  },
  stonebreakYard: {
    label: 'Stonebreak Yard',
    function: 'Ashen stone drop-off and shaping yard',
    asset: 'stonebreakYard',
    maxHp: 340,
    footprint: { width: 4, height: 3 },
    renderSize: 320,
    collisionFootprint: { width: 5.6, height: 4.7 },
    collisionOffset: { x: -2.2, z: -2.2 },
    collisionClearance: 0.72,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 7,
    cost: { food: 0, wood: 45, stone: 20, gold: 0 },
    enemyStructure: true,
    storage: true,
    acceptsResources: ['stone'],
    gatherBonus: { resourceType: 'stone', radius: 15, multiplier: 1.12 },
  },
  oreHearth: {
    label: 'Ore Hearth',
    function: 'Ashen gold drop-off and ore sorting fire',
    asset: 'oreHearth',
    maxHp: 310,
    footprint: { width: 4, height: 3 },
    renderSize: 320,
    collisionFootprint: { width: 5.6, height: 4.7 },
    collisionOffset: { x: -2.2, z: -2.2 },
    collisionClearance: 0.72,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 7,
    cost: { food: 0, wood: 55, stone: 18, gold: 0 },
    enemyStructure: true,
    storage: true,
    acceptsResources: ['gold'],
    gatherBonus: { resourceType: 'gold', radius: 15, multiplier: 1.18 },
  },
  ashenField: {
    label: 'Ashen Crop Plot',
    function: 'One-Hearthkin food plot',
    asset: 'ashenField',
    maxHp: 140,
    footprint: { width: 8, height: 6 },
    renderSize: 420,
    collisionClearance: 0.68,
    interactionSlots: 8,
    entrance: 'south',
    buildTime: 6,
    cost: { food: 0, wood: 25, stone: 0, gold: 0 },
    enemyStructure: true,
    field: true,
    walkable: true,
  },
  ashenWall: {
    label: 'Ashen Stake Wall',
    function: 'Ashen defensive boundary',
    asset: 'ashenWall',
    maxHp: 240,
    footprint: { width: 3, height: 1 },
    renderSize: 190,
    collisionClearance: 0.48,
    interactionSlots: 8,
    buildTime: 4,
    cost: { food: 0, wood: 18, stone: 8, gold: 0 },
    wall: true,
    wallSegmentSpan: 3,
    enemyStructure: true,
  },
  ashenGate: {
    label: 'Ashen Stake Gate',
    function: 'Passable Ashen entryway',
    asset: 'ashenGate',
    maxHp: 280,
    footprint: { width: 3.2, height: 1.35 },
    renderSize: 250,
    collisionClearance: 0.48,
    interactionSlots: 8,
    buildTime: 5,
    cost: { food: 0, wood: 38, stone: 12, gold: 0 },
    gate: true,
    walkable: true,
    enemyStructure: true,
  },
  ashenTower: {
    label: 'Ashen Stake Roost',
    function: 'Reinforced Ashen wall hardpoint',
    asset: 'ashenTower',
    maxHp: 440,
    footprint: { width: 3.6, height: 3.6 },
    renderSize: 300,
    collisionFootprint: { width: 4.2, height: 4.2 },
    collisionOffset: { x: -1.4, z: -1.4 },
    collisionClearance: 0.55,
    allowsUnitOcclusion: true,
    interactionSlots: 8,
    buildTime: 7,
    cost: { food: 0, wood: 75, stone: 18, gold: 0 },
    enemyStructure: true,
  },
};

// Only these structures belong to the current player-facing first-age build
// catalog. Retired prototypes remain defined for old saves/audit history, but
// cannot be placed until they receive an approved Crownforge asset and role.
export const FIRST_AGE_BUILD_BLUEPRINTS = Object.freeze(['barracks', 'stable', 'granary', 'homestead', 'watchHut', 'timberYard', 'stonewrightYard', 'oreWash', 'field', 'road', 'wall', 'gate', 'palisadeTower']);

// First-age doctrine gives the player a small amount of strategic direction
// without introducing a large tech tree. Each upgrade is a one-time local
// rule that is cheap to inspect, save, and balance in the vertical slice.
export const FIRST_AGE_TECHNOLOGIES = Object.freeze({
  forestStewardship: {
    label: 'Forest Stewardship',
    description: 'Crownwardens haul 25% more wood per work cycle.',
    cost: { food: 0, wood: 90, stone: 20, gold: 0 },
    gatherMultiplier: { wood: 1.25 },
  },
  stonecuttersGuild: {
    label: 'Stonecutters Guild',
    description: 'Stone and Gold work cycles yield 15% more.',
    cost: { food: 0, wood: 70, stone: 45, gold: 10 },
    gatherMultiplier: { stone: 1.15, gold: 1.15 },
  },
  watchkeeping: {
    label: 'Watchkeeping',
    description: 'Watch Huts and Palisade Towers see 20% farther.',
    cost: { food: 0, wood: 60, stone: 35, gold: 20 },
    defenseRangeMultiplier: 1.2,
  },
});

// The opening age stays focused when workers have a readable priority rather
// than a full automation tree. These are deliberately small, inspectable
// presets that only change how idle builders choose nearby natural work.
export const FIRST_AGE_WORK_PRIORITIES = Object.freeze({
  balanced: { label: 'Balanced', order: ['wood', 'food', 'stone', 'gold'] },
  wood: { label: 'Wood focus', order: ['wood', 'stone', 'food', 'gold'] },
  food: { label: 'Food focus', order: ['food', 'wood', 'stone', 'gold'] },
  stone: { label: 'Stone focus', order: ['stone', 'gold', 'wood', 'food'] },
  gold: { label: 'Gold focus', order: ['gold', 'stone', 'wood', 'food'] },
});

// Milestones give the First Age a gentle arc without unlocking a later-age
// tech tree. Every requirement is derived from the live slice state or the
// lightweight lifetime haul counter, so it survives save/load cleanly.
export const FIRST_AGE_MILESTONES = Object.freeze([
  { id: 'established', label: 'Establish the Crown Hall', description: 'Keep the settlement core standing.', target: 1 },
  { id: 'provisioned', label: 'Provision the settlement', description: 'Gather 250 total resources.', target: 250 },
  { id: 'frontier', label: 'Open the frontier', description: 'Complete three First Age structures.', target: 3 },
  { id: 'watchful', label: 'Keep watch', description: 'Complete a Watch Hut or Palisade Tower.', target: 1 },
  { id: 'woodland', label: 'Make a clearing', description: 'Clear 12 individual Wildwood trees.', target: 12 },
]);

export const ASSET_RECTS = {
  townCenter: { x: 0, y: 0, width: 418, height: 418 },
  house: { x: 418, y: 0, width: 418, height: 418 },
  storehouse: { x: 836, y: 0, width: 418, height: 418 },
  villager: { x: 0, y: 418, width: 418, height: 418 },
  soldier: { x: 418, y: 418, width: 418, height: 418 },
  raider: { x: 836, y: 418, width: 418, height: 418 },
  tree: { x: 0, y: 836, width: 418, height: 418 },
  berry: { x: 418, y: 836, width: 418, height: 418 },
  stone: { x: 836, y: 836, width: 418, height: 418 },
};

export const ENVIRONMENT_ATLAS = {
  src: './assets/crownforge-environment-atlas-v3.png?v=1',
  width: 1254,
  height: 1254,
  columns: 4,
  rows: 4,
  // Alpha-audited baseline for the visible soil/foliage contact band. The
  // former rectangle-bottom anchor left every tree, bush, stone, and stump a
  // few pixels above the meadow.
  groundAnchorY: 0.944,
  rowByType: { tree: 0, berry: 1, stone: 2, log: 3, stump: 3, flowers: 3, pebbles: 3 },
};

// Trees have their own cropped atlas so a tree cell can never sample berries,
// stone, or a neighboring row. The source family remains the same Crownforge
// environment treatment; this boundary is a rendering safeguard.
export const TREE_ATLAS = {
  src: './assets/crownforge-tree-atlas-v1.png?v=20260819-fieldpass1',
  width: 1254,
  height: 313,
  columns: 4,
  rows: 1,
  groundAnchorY: 0.9453,
};

export const TREE_GROVE_ATLAS = {
  src: './assets/crownforge-tree-grove-depletion-v1.png?v=20260818-sandbox1',
  width: 1230,
  height: 1278,
  columns: 2,
  rows: 2,
  groundAnchorByCell: {
    '0,0': 0.989,
    '1,0': 0.9984,
    '0,1': 0.9011,
    '1,1': 0.8917,
  },
};

export const ANCIENT_FOREST_ATLAS = {
  src: './assets/crownforge-ancient-forest-depletion-v1.png?v=20260825-demoforest1',
  width: 1254,
  height: 1254,
  columns: 2,
  rows: 2,
  groundAnchorByCell: {
    '0,0': 0.9824,
    '1,0': 0.9824,
    '0,1': 0.9488,
    '1,1': 0.96,
  },
};

export const WILDWOOD_FOREST_ATLAS = {
  src: './assets/crownforge-wildwood-depletion-v2.png?v=20260830-renderguard1',
  width: 1536,
  height: 1024,
  columns: 3,
  rows: 2,
  groundAnchorByCell: {
    '0,0': 0.8652,
    '1,0': 0.9102,
    '2,0': 0.9102,
    '0,1': 0.875,
    '1,1': 0.877,
    '2,1': 0.875,
  },
};

export const LARGE_STONE_ASSET = {
  src: './assets/crownforge-stone-deposit-large-v1.png?v=20260819-unitpass3',
  width: 1536,
  height: 1024,
  groundAnchorY: 0.9561,
};

// Gold uses a small authored family rather than recoloring the stone atlas.
// Each tier has its own silhouette, and exhausted veins retain a low worked
// rubble state so depletion reads without a floating label.
export const GOLD_DEPOSIT_ASSETS = {
  small: { src: './assets/crownforge-gold-deposit-small-v1.png?v=20260822-goldpass1', width: 1536, height: 1024, groundAnchorY: 0.8018 },
  medium: { src: './assets/crownforge-gold-deposit-medium-v1.png?v=20260822-goldpass1', width: 1536, height: 1024, groundAnchorY: 0.959 },
  large: { src: './assets/crownforge-gold-deposit-large-v1.png?v=20260822-goldpass1', width: 1536, height: 1024, groundAnchorY: 0.9365 },
  depleted: { src: './assets/crownforge-gold-deposit-depleted-v1.png?v=20260822-goldpass1', width: 1536, height: 1024, groundAnchorY: 0.8936 },
};

export const FIRST_AGE_ASSETS = {
  townCenter: { src: './assets/crownforge-crown-hall-wood-v1.png?v=20260821-hallwoodpass2', width: 1536, height: 1024, groundAnchorY: 0.9404 },
  barracks: { src: './assets/crownforge-barracks-first-age-v3.png?v=20260822-uprightwalls2', width: 1536, height: 1024, groundAnchorY: 0.9355 },
  stable: {
    src: './assets/crownforge-stable-first-age-v1.png?v=20260824-firstage1',
    width: 1536,
    height: 1024,
    groundAnchorY: 0.9209,
    constructionAtlas: {
      src: './assets/crownforge-stable-construction-atlas-v1.png?v=20260824-firstage1',
      width: 1536,
      height: 1024,
      columns: 2,
      rows: 2,
      destinationAspect: 512 / 768,
      groundAnchorByCell: { '0,0': 0.9196, '1,0': 0.9294, '0,1': 0.9235 },
      cellByStage: {
        foundation: { column: 0, row: 0 },
        partial: { column: 1, row: 0 },
        nearComplete: { column: 0, row: 1 },
      },
    },
  },
  watchHut: {
    src: './assets/crownforge-watch-hut-first-age-v1.png?v=20260825-firstage4',
    width: 1300,
    height: 1209,
    groundAnchorY: 0.9636,
    constructionAtlas: {
      src: './assets/crownforge-watch-hut-construction-atlas-v1.png?v=20260825-firstage4',
      width: 1536,
      height: 1024,
      columns: 2,
      rows: 2,
      destinationAspect: 512 / 768,
      groundAnchorByCell: { '0,0': 0.998, '1,0': 0.998, '0,1': 0.9647 },
      cellByStage: {
        foundation: { column: 0, row: 0 },
        partial: { column: 1, row: 0 },
        nearComplete: { column: 0, row: 1 },
      },
    },
  },
  granary: {
    src: './assets/crownforge-granary-first-age-v1.png?v=20260824-firstage1',
    width: 1536,
    height: 1024,
    groundAnchorY: 0.8799,
    constructionAtlas: {
      src: './assets/crownforge-granary-construction-atlas-v1.png?v=20260824-firstage1',
      width: 1536,
      height: 1024,
      columns: 2,
      rows: 2,
      destinationAspect: 512 / 768,
      groundAnchorByCell: { '0,0': 0.9373, '1,0': 0.9588, '0,1': 0.9176 },
      cellByStage: {
        foundation: { column: 0, row: 0 },
        partial: { column: 1, row: 0 },
        nearComplete: { column: 0, row: 1 },
      },
    },
  },
  homestead: {
    src: './assets/crownforge-homestead-first-age-v1.png?v=20260824-firstage3',
    width: 1536,
    height: 1024,
    groundAnchorY: 0.9609,
    constructionAtlas: {
      src: './assets/crownforge-homestead-construction-atlas-v1.png?v=20260824-firstage3',
      width: 1536,
      height: 1024,
      columns: 2,
      rows: 2,
      destinationAspect: 512 / 768,
      groundAnchorByCell: { '0,0': 0.998, '1,0': 0.998, '0,1': 0.851 },
      cellByStage: {
        foundation: { column: 0, row: 0 },
        partial: { column: 1, row: 0 },
        nearComplete: { column: 0, row: 1 },
      },
    },
  },
  timberYard: {
    src: './assets/crownforge-timber-yard-first-age-v1.png?v=20260824-firstage2',
    width: 1536,
    height: 1024,
    groundAnchorY: 0.9326,
    constructionAtlas: {
      src: './assets/crownforge-timber-yard-construction-atlas-v1.png?v=20260824-firstage2',
      width: 1536,
      height: 1024,
      columns: 2,
      rows: 2,
      destinationAspect: 512 / 768,
      groundAnchorByCell: { '0,0': 0.998, '1,0': 0.998, '0,1': 0.9314 },
      cellByStage: {
        foundation: { column: 0, row: 0 },
        partial: { column: 1, row: 0 },
        nearComplete: { column: 0, row: 1 },
      },
    },
  },
  stonewrightYard: {
    src: './assets/crownforge-stonewright-yard-first-age-v1.png?v=20260824-firstage2',
    width: 1536,
    height: 1024,
    groundAnchorY: 0.9473,
    constructionAtlas: {
      src: './assets/crownforge-stonewright-yard-construction-atlas-v1.png?v=20260824-firstage2',
      width: 1536,
      height: 1024,
      columns: 2,
      rows: 2,
      destinationAspect: 512 / 768,
      groundAnchorByCell: { '0,0': 0.9294, '1,0': 0.998, '0,1': 0.9569 },
      cellByStage: {
        foundation: { column: 0, row: 0 },
        partial: { column: 1, row: 0 },
        nearComplete: { column: 0, row: 1 },
      },
    },
  },
  oreWash: {
    src: './assets/crownforge-ore-wash-v1.png?v=20260823-orewashstages1',
    width: 1536,
    height: 1024,
    groundAnchorY: 0.9248,
    constructionStages: {
      foundation: { src: './assets/crownforge-ore-wash-foundation-v1.png?v=20260823-orewashstages1', width: 1536, height: 1024, groundAnchorY: 0.916 },
      partial: { src: './assets/crownforge-ore-wash-partial-v1.png?v=20260823-orewashstages1', width: 1536, height: 1024, groundAnchorY: 0.9248 },
      nearComplete: { src: './assets/crownforge-ore-wash-near-complete-v1.png?v=20260823-orewashstages1', width: 1536, height: 1024, groundAnchorY: 0.9248 },
    },
  },
  lumberMill: { src: './assets/crownforge-lumber-mill-v1.png?v=20260818-sandbox1', width: 1254, height: 1254, groundAnchorY: 0.8285 },
  quarry: { src: './assets/crownforge-quarry-v1.png?v=20260818-sandbox1', width: 1254, height: 1254, groundAnchorY: 0.9242 },
  grainMill: { src: './assets/crownforge-grain-mill-v1.png?v=20260818-sandbox1', width: 1254, height: 1254, groundAnchorY: 0.878 },
  field: { src: './assets/crownforge-field-v2.png?v=20260819-fieldpass1', width: 1536, height: 1024, groundAnchorY: 0.9697 },
  road: { src: './assets/crownforge-dirt-road-tile-v1.png?v=20260831-firstage2', width: 1024, height: 1024, groundAnchorY: 0.5 },
  // Palisades use authored screen-space views instead of rotating one flat
  // picture. Rotating an upright fence also rotates its posts and makes a
  // completed wall look as if it is lying on the meadow.
  // A fortification anchor is the center of its footprint on the meadow,
  // never the lowest opaque pixel. Each authored view has a different amount
  // of perspective depth, so one generic bottom anchor made turns climb or
  // drop when two otherwise-correct panels met.
  wall: { src: './assets/crownforge-palisade-diagonal-right-v1.png?v=20260827-fortificationanchors1', width: 1536, height: 1024, groundAnchorY: 0.815 },
  wallDiagonalLeft: { src: './assets/crownforge-palisade-diagonal-left-v1.png?v=20260827-fortificationanchors1', width: 1536, height: 1024, groundAnchorY: 0.825 },
  wallFace: { src: './assets/crownforge-palisade-face-v1.png?v=20260827-fortificationanchors1', width: 1536, height: 1024, groundAnchorY: 0.83 },
  wallDepth: { src: './assets/crownforge-palisade-depth-v1.png?v=20260827-fortificationanchors1', width: 1536, height: 1024, groundAnchorY: 0.5 },
  // The gate is a 2x2 atlas so each upright screen-space wall direction gets
  // its own matching opening instead of rotating a flat picture.
  gate: {
    src: './assets/crownforge-palisade-gate-atlas-v2.png?v=20260827-fortificationanchors1',
    width: 1254,
    height: 1254,
    columns: 2,
    rows: 2,
    groundAnchorByCell: { '0,0': 0.94, '1,0': 0.95, '0,1': 0.972, '1,1': 0.86 },
    cellByOrientation: {
      // The atlas's top-left opening rises to screen-right (diagonal-left),
      // while the top-right opening falls to screen-right (diagonal-right).
      // These two cells were previously reversed even though the stored
      // orientation metadata itself was correct.
      'diagonal-right': { column: 1, row: 0 },
      'diagonal-left': { column: 0, row: 0 },
      face: { column: 0, row: 1 },
      depth: { column: 1, row: 1 },
    },
  },
  palisadeTower: {
    src: './assets/crownforge-palisade-tower-first-age-v1.png?v=20260827-fortificationanchors1',
    width: 1254,
    height: 1254,
    groundAnchorY: 0.85,
    constructionAtlas: {
      src: './assets/crownforge-palisade-tower-construction-atlas-v1.png?v=20260827-fortificationanchors1',
      width: 1254,
      height: 1254,
      columns: 2,
      rows: 2,
      destinationAspect: 1,
      // All three stages use the same footprint center. The earlier
      // lowest-pixel anchors visibly moved the tower down and right as it was
      // built even though its simulation socket never changed.
      groundAnchorByCell: { '0,0': 0.72, '1,0': 0.82, '0,1': 0.82 },
      cellByStage: {
        foundation: { column: 0, row: 0 },
        partial: { column: 1, row: 0 },
        nearComplete: { column: 0, row: 1 },
      },
    },
  },
  palisadeJunction: {
    src: './assets/crownforge-palisade-junction-post-v1.png?v=20260827-fortificationanchors1',
    width: 1254,
    height: 1254,
    groundAnchorY: 0.82,
  },
};

// Ashen equivalents share the Crownforge camera, scale, and lighting rules,
// but never reuse Crownwarden architecture. Direct landmark images and two
// compact atlases keep the rival settlement coherent without multiplying
// one-off render paths for every small work yard.
const ASHEN_CONSTRUCTION_ATLAS = {
  src: './assets/crownforge-ashen-construction-stages-v1.png?v=20260826-ashensettlement1',
  width: 1254,
  height: 1254,
  columns: 2,
  rows: 2,
  groundAnchorY: 0.9776,
  cellByStage: {
    foundation: { column: 0, row: 0 },
    partial: { column: 1, row: 0 },
    nearComplete: { column: 0, row: 1 },
  },
};

const ASHEN_SUPPORT_ATLAS = {
  src: './assets/crownforge-ashen-support-buildings-v1.png?v=20260826-ashensettlement1',
  width: 1254,
  height: 1254,
  columns: 3,
  rows: 3,
  groundAnchorY: 0.9663,
};

const ASHEN_FORTIFICATION_ATLAS = {
  src: './assets/crownforge-ashen-fortifications-v1.png?v=20260826-ashensettlement1',
  width: 1254,
  height: 1254,
  columns: 4,
  rows: 4,
};

export const ASHEN_BUILDING_ASSETS = {
  ashenCamp: {
    src: './assets/crownforge-ashen-hearth-v1.png?v=20260826-ashensettlement1',
    width: 1536,
    height: 1024,
    groundAnchorY: 0.9707,
  },
  reaverLodge: {
    src: './assets/crownforge-reaver-lodge-v1.png?v=20260826-ashensettlement1',
    width: 1536,
    height: 1024,
    groundAnchorY: 0.9863,
    constructionAtlas: ASHEN_CONSTRUCTION_ATLAS,
  },
  beastCorral: {
    src: './assets/crownforge-beast-corral-v1.png?v=20260826-ashensettlement1',
    width: 1536,
    height: 1024,
    groundAnchorY: 0.9873,
    constructionAtlas: ASHEN_CONSTRUCTION_ATLAS,
  },
  smokeGranary: { atlas: ASHEN_SUPPORT_ATLAS, cell: { column: 0, row: 0 }, constructionAtlas: ASHEN_CONSTRUCTION_ATLAS },
  hideHomestead: { atlas: ASHEN_SUPPORT_ATLAS, cell: { column: 1, row: 0 }, constructionAtlas: ASHEN_CONSTRUCTION_ATLAS },
  signalRoost: { atlas: ASHEN_SUPPORT_ATLAS, cell: { column: 2, row: 0 }, constructionAtlas: ASHEN_CONSTRUCTION_ATLAS },
  ashenTimberRack: { atlas: ASHEN_SUPPORT_ATLAS, cell: { column: 0, row: 1 }, constructionAtlas: ASHEN_CONSTRUCTION_ATLAS },
  stonebreakYard: { atlas: ASHEN_SUPPORT_ATLAS, cell: { column: 1, row: 1 }, constructionAtlas: ASHEN_CONSTRUCTION_ATLAS },
  oreHearth: { atlas: ASHEN_SUPPORT_ATLAS, cell: { column: 2, row: 1 }, constructionAtlas: ASHEN_CONSTRUCTION_ATLAS },
  ashenField: { atlas: ASHEN_SUPPORT_ATLAS, cell: { column: 0, row: 2 }, constructionAtlas: ASHEN_CONSTRUCTION_ATLAS },
  ashenWall: {
    atlas: ASHEN_FORTIFICATION_ATLAS,
    cellByOrientation: {
      'diagonal-right': { column: 0, row: 0 },
      'diagonal-left': { column: 1, row: 0 },
      face: { column: 2, row: 0 },
      depth: { column: 3, row: 0 },
    },
    constructionAtlas: ASHEN_CONSTRUCTION_ATLAS,
  },
  ashenGate: {
    atlas: ASHEN_FORTIFICATION_ATLAS,
    cellByOrientation: {
      'diagonal-right': { column: 0, row: 1 },
      'diagonal-left': { column: 1, row: 1 },
      face: { column: 2, row: 1 },
      depth: { column: 3, row: 1 },
    },
    constructionAtlas: ASHEN_CONSTRUCTION_ATLAS,
  },
  ashenTower: {
    atlas: ASHEN_FORTIFICATION_ATLAS,
    cellByOrientation: {
      'diagonal-right': { column: 0, row: 2 },
      'diagonal-left': { column: 1, row: 2 },
      face: { column: 2, row: 2 },
      depth: { column: 3, row: 2 },
    },
    constructionAtlas: ASHEN_CONSTRUCTION_ATLAS,
  },
};

export const ROAD_DETAILS_ATLAS = {
  src: './assets/crownforge-roadside-props-v1.png?v=20260818-roads2',
  width: 1536,
  height: 1024,
  columns: 2,
  rows: 2,
  // The source sheet is a 2x2 plate rather than a square atlas so the fence
  // and sign keep their authored proportions when sampled by the renderer.
  columnByType: { fence: 0, sign: 1, cargo: 0, lantern: 1 },
  rowByType: { fence: 0, sign: 0, cargo: 1, lantern: 1 },
};

export const BUILDING_STAGE_ATLAS = {
  src: './assets/crownforge-building-stages-v2.png?v=3',
  width: 1254,
  height: 1254,
  columns: 4,
  rows: 4,
  columnByType: { townCenter: 0, house: 1, storehouse: 2 },
  rowByStage: { foundation: 0, partial: 1, nearComplete: 2, complete: 3 },
};

export const ENEMY_CAMP_ASSET = {
  src: './assets/crownforge-ashen-hearth-v1.png?v=20260826-ashensettlement1',
  width: 1536,
  height: 1024,
};

export const VILLAGER_ATLASES = {
  motion: {
    src: './assets/villager-motion-atlas.png?v=2',
    rows: { idle: 0, walk: [1, 2, 3] },
  },
  motionLoop: {
    src: './assets/crownforge-villager-walk-loop-v4.png?v=20260902-hearthkinmotion1',
    width: 1242,
    height: 1266,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
    directionRows: [0, 1, 2, 3],
  },
  task: {
    src: './assets/villager-task-atlas.png?v=2',
    rows: { wood: 0, food: 1, stone: 2, build: 3 },
  },
  carry: {
    src: './assets/villager-carry-atlas.png?v=2',
    rows: { wood: 0, food: 1, stone: 2, supplies: 3 },
  },
  combat: {
    src: './assets/villager-combat-atlas.png?v=2',
    rows: { attack: 0, hit: 1, death: 2, idle: 3 },
  },
  defenseAttackLoop: {
    src: './assets/crownforge-villager-defense-attack-loop-v1.png?v=20260826-lastlight1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  statusEffects: {
    src: './assets/crownforge-last-light-status-effects-v1.png?v=20260826-lastlight1',
    width: 1254,
    height: 1254,
    columns: 2,
    rows: 2,
    layout: 'frame-columns',
    cells: {
      wardA: { column: 0, row: 0 },
      wardB: { column: 1, row: 0 },
      stunned: { column: 0, row: 1 },
      stunImmune: { column: 1, row: 1 },
    },
  },
  hitLoop: {
    src: './assets/villager-hit-loop-v1.png?v=20260821-hallwoodpass2',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  deathLoop: {
    src: './assets/villager-death-loop-v1.png?v=20260821-hallwoodpass2',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  // Action-loop atlases use frame columns and authored direction rows. The
  // legacy task/carry/combat sheets remain available for states that are
  // intentionally single-pose, while newer focused passes can replace a
  // response family without changing the shared renderer contract.
  woodLoop: {
    src: './assets/villager-gather-wood-loop-v1.png?v=1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  foodLoop: {
    src: './assets/villager-gather-food-loop-v1.png?v=1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  fieldLoop: {
    src: './assets/crownforge-villager-field-work-loop-v1.png?v=20260819-fieldpass1',
    width: 1235,
    height: 1274,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  stoneLoop: {
    src: './assets/villager-gather-stone-loop-v1.png?v=1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  buildLoop: {
    src: './assets/villager-construct-loop-v1.png?v=1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  carryWoodLoop: {
    src: './assets/villager-carry-wood-loop-v1.png?v=1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  carryFoodLoop: {
    src: './assets/villager-carry-food-loop-v1.png?v=1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  carryStoneLoop: {
    src: './assets/villager-carry-stone-loop-v1.png?v=1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  carryGoldLoop: {
    src: './assets/crownforge-villager-carry-gold-loop-v1.png?v=20260822-goldpass1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  carrySuppliesLoop: {
    src: './assets/villager-carry-supplies-loop-v1.png?v=1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  columns: 4,
  rows: 4,
  width: 1254,
  height: 1254,
};

export const COMBAT_ATLASES = {
  soldier: {
    src: './assets/crownforge-soldier-combat-atlas-v1.png?v=1',
    width: 1243,
    height: 1265,
    columns: 4,
    rows: 4,
    rowByState: { idle: 0, walk: 1, attack: 2, death: 3 },
  },
  soldierAttack: {
    src: './assets/crownforge-soldier-attack-loop-v1.png?v=1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  soldierWalk: {
    src: './assets/crownforge-soldier-walk-loop-v3.png?v=20260819-unitpass3',
    width: 1224,
    height: 1285,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  soldierHit: {
    src: './assets/crownforge-soldier-hit-loop-v1.png?v=20260820-hitpass1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  soldierDeath: {
    src: './assets/crownforge-soldier-death-loop-v1.png?v=20260820-hitpass1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  raider: {
    src: './assets/crownforge-raider-combat-atlas-v1.png?v=1',
    width: 1243,
    height: 1266,
    columns: 4,
    rows: 4,
    rowByState: { idle: 0, walk: 1, attack: 2, death: 3 },
  },
  raiderAttack: {
    src: './assets/crownforge-raider-attack-loop-v4.png?v=20260819-unitpass3',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  raiderWalk: {
    src: './assets/crownforge-raider-walk-loop-v2.png?v=20260819-unitpass3',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  raiderHit: {
    src: './assets/crownforge-raider-hit-loop-v1.png?v=20260820-hitpass1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  raiderStunned: {
    src: './assets/crownforge-raider-stunned-loop-v1.png?v=20260826-lastlight1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  raiderDeath: {
    src: './assets/crownforge-raider-death-loop-v1.png?v=20260820-hitpass1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  scout: {
    src: './assets/crownforge-scout-combat-atlas-v3.png?v=20260825-scoutscale2',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    rowByState: { idle: 0, walk: 1, attack: 2, death: 3 },
  },
  scoutWalk: {
    src: './assets/crownforge-scout-walk-loop-v3.png?v=20260825-scoutscale2',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  scoutAttack: {
    src: './assets/crownforge-scout-attack-loop-v3.png?v=20260825-scoutscale2',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  spearwarden: {
    src: './assets/crownforge-spearwarden-combat-atlas-v1.png?v=20260824-firstage2',
    width: 1233,
    height: 1275,
    columns: 4,
    rows: 4,
    rowByState: { idle: 0, walk: 1, attack: 2, death: 3 },
  },
  spearwardenWalk: {
    src: './assets/crownforge-spearwarden-walk-loop-v1.png?v=20260824-firstage2',
    width: 1230,
    height: 1278,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  spearwardenAttack: {
    src: './assets/crownforge-spearwarden-attack-loop-v1.png?v=20260824-firstage2',
    width: 1268,
    height: 1241,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  militia: {
    src: './assets/crownforge-militia-combat-atlas-v1.png?v=20260824-firstage3',
    width: 1224,
    height: 1285,
    columns: 4,
    rows: 4,
    rowByState: { idle: 0, walk: 1, attack: 2, death: 3 },
  },
  militiaWalk: {
    src: './assets/crownforge-militia-walk-loop-v1.png?v=20260824-firstage3',
    width: 1240,
    height: 1268,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  militiaAttack: {
    src: './assets/crownforge-militia-attack-loop-v1.png?v=20260824-firstage3',
    width: 1536,
    height: 1024,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  shieldbearer: {
    src: './assets/crownforge-shieldbearer-combat-atlas-v1.png?v=20260825-firstage4',
    width: 1230,
    height: 1278,
    columns: 4,
    rows: 4,
    rowByState: { idle: 0, walk: 1, attack: 2, death: 3 },
  },
  shieldbearerWalk: {
    src: './assets/crownforge-shieldbearer-walk-loop-v1.png?v=20260825-firstage4',
    width: 1239,
    height: 1269,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  shieldbearerAttack: {
    src: './assets/crownforge-shieldbearer-attack-loop-v1.png?v=20260825-firstage4',
    width: 1236,
    height: 1273,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  ashenForagerMotion: {
    src: './assets/crownforge-ashen-forager-motion-v1.png?v=20260826-ashensettlement1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
    rowByState: { idle: 0 },
  },
  ashenForagerWork: {
    src: './assets/crownforge-ashen-forager-work-v1.png?v=20260826-ashensettlement1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  ashenForagerCarry: {
    src: './assets/crownforge-ashen-forager-carry-v1.png?v=20260826-ashensettlement1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  ashenOutriderMotion: {
    src: './assets/crownforge-ashen-outrider-motion-v1.png?v=20260826-ashensettlement1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
    rowByState: { idle: 0 },
  },
  ashenOutriderAttack: {
    src: './assets/crownforge-ashen-outrider-attack-v1.png?v=20260826-ashensettlement1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  thornSpearMotion: {
    src: './assets/crownforge-thorn-spear-motion-v1.png?v=20260826-ashensettlement1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
    rowByState: { idle: 0 },
  },
  thornSpearAttack: {
    src: './assets/crownforge-thorn-spear-attack-v1.png?v=20260826-ashensettlement1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  hearthLevyMotion: {
    src: './assets/crownforge-hearth-levy-motion-v1.png?v=20260826-ashensettlement1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
    rowByState: { idle: 0 },
  },
  hearthLevyAttack: {
    src: './assets/crownforge-hearth-levy-attack-v1.png?v=20260826-ashensettlement1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
  hidewallMotion: {
    src: './assets/crownforge-hidewall-motion-v1.png?v=20260826-ashensettlement1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
    rowByState: { idle: 0 },
  },
  hidewallAttack: {
    src: './assets/crownforge-hidewall-attack-v1.png?v=20260826-ashensettlement1',
    width: 1254,
    height: 1254,
    columns: 4,
    rows: 4,
    layout: 'frame-columns',
  },
};

export const INITIAL_RESOURCES = { food: 5000, wood: 5000, stone: 5000, gold: 5000 };
