import {SKYBREAKER_ART,SKYBREAKER_LORE} from './storm-dragon.js?v=20260921-militiaplay1';
export const lastCrownMercyActive=unit=>Boolean(unit&&!unit.dead&&unit.hp>0&&UNIT_TYPES[unit.type]?.combatRole==='tank'&&unit.hp/unit.maxHp<.1);
import {deathlessActive,updateDeathlessHeart,deathlessCrossingDamage} from './deathless-heart.js?v=20260921-militiaplay1';
import { bearVariant } from './bear-variants.js?v=20260921-militiaplay1';
import {UNIT_TYPES} from './config.js?v=20260921-militiaplay1';
import {bearCrowdMultiplier,BEAR_FURY,bearFuryActive,bearEnrageActive,isFighter} from './bear-combat.js?v=20260921-militiaplay1';

export const FIRST_CONDEMNATION = Object.freeze({
  id:'firstCondemnation',name:'The First Condemnation',kind:'Permanent elder magic',
  summary:'The old gods do not forgive. The bloodline does not forget.',
  lore:'When the first kings felled the grove that held the sleeping stars, the old gods called the grizzlies of the Greatwood to judgment. The bears had devoured the grove’s keepers. For that hunger, every generation of their blood was bound to guard the forest they had betrayed. The First Condemnation is no passing spell: it is a law laid beneath flesh and bone. Sorcery born after that ancient sentence cannot unmake it. Only the hands that shaped the first dawn may rewrite its terms.',
  effect:'Bound to guard the forest they betrayed. This ancestral curse cannot be dispelled; only the old gods can lift it.',
  art:'./assets/crownforge-first-condemnation-v1.png?v=20260906-firstcondemnation1',
});
export const GREATWOOD_FURY_ART='./assets/greatwood-fury-card-v1.png?v=20260909-bearfury1';
export const isCurseImmune=unit=>Boolean(UNIT_TYPES[unit?.type]?.curseImmune);
export const isWardProtected=unit=>Boolean(unit?.lastLightWardTimer>0||unit?.type==='wizard'&&unit.eventideVeil>0);
// Portraits and combat always use the unit's real health.
export const displayedUnitHealth=unit=>unit.dead?0:unit.hp;
export const LAST_BASTION=Object.freeze({threshold:.2,rearmHealth:.6,damageMultiplier:.1,tankDuration:20,bearDuration:60});
const lastStandUnit=u=>u?.type==='shieldbearer'||u?.type==='grizzly';
export const lastBastionActive=u=>Boolean(lastStandUnit(u)&&!u.dead&&u.hp>0&&u.hp/u.maxHp<=LAST_BASTION.rearmHealth&&(u.lastStandTimer??0)>0);
export function updateLastBastion(unit,dt=0){
 updateDeathlessHeart(unit,dt);
 if(!lastStandUnit(unit))return;
 if(unit.dead||unit.hp<=0){unit.lastStandTimer=0;return;}
 if(unit.hp/unit.maxHp>LAST_BASTION.rearmHealth){unit.lastStandTimer=0;unit.lastStandSpent=false;return;}
 const activeTime=Math.min(Math.max(0,dt),unit.lastStandTimer??0);
 if(unit.type==='grizzly'&&activeTime>0){
  unit.lastStandHealElapsed=(unit.lastStandHealElapsed??0)+activeTime;
  const pulses=Math.floor((unit.lastStandHealElapsed+1e-8)/5);
  if(pulses){unit.lastStandHealElapsed-=pulses*5;const amount=Math.min(unit.maxHp-unit.hp,unit.maxHp*.02*Math.min(pulses,Math.floor((unit.maxHp*.6-unit.hp)/(unit.maxHp*.02))+1));unit.hp+=amount;unit.healPulse=.85;unit.lastHealAmount=amount;unit.healthRevealTimer=2;}
 }
 unit.lastStandTimer=Math.max(0,(unit.lastStandTimer??0)-dt);
 if(unit.hp/unit.maxHp>LAST_BASTION.rearmHealth){unit.lastStandTimer=0;unit.lastStandSpent=false;return;}
 if(!unit.lastStandSpent&&unit.hp/unit.maxHp<LAST_BASTION.threshold){
  unit.lastStandHealElapsed=0;unit.lastStandSpent=true;unit.lastStandTimer=unit.type==='grizzly'?LAST_BASTION.bearDuration:LAST_BASTION.tankDuration;
 }
}
// Protect only the below-threshold portion of the first crossing hit.
function ordinaryBastionDamage(unit,damage){
 if(!lastStandUnit(unit)||unit.dead||unit.hp<=0)return damage;
 updateLastBastion(unit);
 if(lastBastionActive(unit))return damage*LAST_BASTION.damageMultiplier;
 if(unit.lastStandSpent)return damage;
 const unprotected=Math.max(0,unit.hp-unit.maxHp*LAST_BASTION.threshold);
 if(damage<=unprotected)return damage;
 unit.lastStandHealElapsed=0;unit.lastStandSpent=true;unit.lastStandTimer=unit.type==='grizzly'?LAST_BASTION.bearDuration:LAST_BASTION.tankDuration;
 return unprotected+(damage-unprotected)*LAST_BASTION.damageMultiplier;
}
export function lastBastionDamage(unit,damage){
 if(!lastStandUnit(unit)||unit.dead||unit.hp<=0)return damage;
 updateLastBastion(unit);
 if(deathlessActive(unit))return damage*.01;
 const ordinary=ordinaryBastionDamage(unit,damage);
 return deathlessCrossingDamage(unit,damage,ordinary,lastBastionActive(unit)?.1:1);
}
export function strikeDamage(attacker,target){
  const rules=UNIT_TYPES[attacker.type],worker=UNIT_TYPES[target?.type]?.worker;
  const tankPressure=attacker.type==='grizzly'&&UNIT_TYPES[target?.type]?.combatRole==='tank'?6:1;
  const base=bearCrowdMultiplier(attacker)*tankPressure*(bearEnrageActive(attacker)?2:1)*(rules.workerStrikeFraction&&worker?Math.ceil(target.maxHp*rules.workerStrikeFraction):worker?(rules.attackVsVillager??rules.attack):rules.attack);
  if(!bearFuryActive(attacker))return base;
  const empowered=base*BEAR_FURY.multiplier;
  return isFighter(target)&&UNIT_TYPES[target.type]?.combatRole!=='tank'?Math.max(empowered,target.hp):empowered;
}
export function unitStatuses(unit){
  const statuses=[],elder=isCurseImmune(unit),fury=bearFuryActive(unit);
  if(unit.type==="soldier")statuses.push({"id": "crownGuardOath", "name": "The Watch That Never Ends", "kind": "Crown Guard", "detail": "Sworn to the watch", "summary": "A kingdom sleeps because someone stays awake.", "lore": "In the winter of the Unlit Road, the Crown sent its soldiers home before the mountain passes closed. One gate captain refused to draw the bar. Three wagons were still missing, and she knew the names of the drivers. Her company carried lanterns into the snow. At dawn they returned with frost-blackened hands, two broken axles, and every traveler accounted for.\n\nThe Crown Guard still calls its evening muster the Counting of Lights. A recruit learns the roads, the households, and the sound of trouble before earning a place at the gate. There are sword drills until the wrists ache, long patrols in weather no one remembers, and quiet decisions made with a frightened stranger watching. Their authority is measured by how safely another person can pass beneath it.\n\nWhen war comes, those same soldiers march at the front of the Crownlands. They know what lies behind the walls because they have kept watch over it. At each change of guard, one lantern passes from hand to hand. The soldier may rest. The watch goes on.", "effect": "A trained melee soldier, equipped with sword and shield to defend the settlement.", "art": "./assets/crown-guard/watch-lore-v1.png", "rune": "ward"});
  if(unit.type==="militia")statuses.push({"id": "militiaOath", "name": "When the Bells Call", "kind": "Crown Militia", "detail": "Neighbors under arms", "summary": "Every bell has a voice. Every village has an answer.", "lore": "The first militia roll was written on the back of a baker’s account book. Raiders had cut the road, the garrison was two days away, and the village bell was ringing. A cooper brought a wooden shield. A mason carried an iron mace from the storehouse. One by one, names usually called across a market square answered from behind the barricade.\n\nThe Crown later sent weapons, instructors, and a banner. The villagers kept the book. Its pages taught each new company that courage needed practice: how to brace a shield, keep a weapon clear of a neighbor, and carry the wounded through a narrow door. They trained after work and before harvest, until the bell could call a company instead of a frightened crowd.\n\nTheir armor is plain, their shields repaired more often than replaced. But every lane has a name they know, and every rooftop shelters someone who will wait for them. When the bells call, they come with trembling hands and familiar faces. They come because the person beside them came too.", "effect": "A lightly armored melee defender, fighting with mace and shield.", "art": "./assets/militia/bells-lore-v1.png", "rune": "ward"});
  if(unit.stormwardTimer>0)statuses.push({id:'stormwardCovenant',name:'Stormward Covenant',kind:'Dragon blessing',detail:`${Math.ceil(unit.stormwardTimer)}s · 30% less damage`,summary:'Thunder shelters those beneath its wings.',effect:'Reduces all incoming damage by 30% for 12 seconds. Granted to allies within 28 units when Heavenrend is summoned.',rune:'ward',art:SKYBREAKER_ART});
  if(unit.skybreakerFavor>0)statuses.push({id:'skybreakerFavor',name:'Skybreaker’s Favor',kind:'Dragon blessing',detail:`${Math.ceil(unit.skybreakerFavor)}s · +50% Starshard damage`,summary:'A stolen star remembers the first thunder.',effect:'Empowers the wizard’s basic star projectile for 12 seconds, raising its damage from 36 to 54.',rune:'fury',art:SKYBREAKER_ART});
  if(unit.type==='wizard'){
   statuses.push({id:'heavenrend',name:'Heavenrend · Call the Skybreaker',kind:'Dragon summon',detail:unit.skybreakerCooldown>0?`${Math.ceil(unit.skybreakerCooldown)}s until ready`:'Ready · five-minute cooldown',summary:'The horizon bows beneath his wings.',lore:SKYBREAKER_LORE,effect:'Select this wizard and press Call the Skybreaker. Summons Vaelthryx for a 10-second flyover, sweeping lightning for 6 seconds: 150 magic AoE damage every half-second within 12 units of the moving breath. 45-unit targeting range; 300-second cooldown.',rune:'divine',art:SKYBREAKER_ART});
   if(unit.skybreakerActive>0)statuses.push({id:'unboundSovereign',name:'Unbound Sovereign',kind:'Aerial ally',detail:`${Math.ceil(unit.skybreakerActive)}s · Vaelthryx is airborne`,summary:'No throne commands him. No chain can hold him.',effect:'An untargetable aerial ally. Flies over terrain and completes his flight even if his summoner falls.',rune:'ward',art:SKYBREAKER_ART});
   const art='./assets/starveil/portrait-v5.png';
   statuses.push({id:'starveilOath',name:'Keeper of the Last Star',kind:'Starveil Arcanist',detail:'One living arcanist per side',summary:'The heavens went silent. One star answered.',lore:'Before he wore the starwoven mantle, the Arcanist was a keeper of forgotten names. In the ruins above the Crownlands, he charted the places where stars had vanished and refused to call that darkness empty. When one last ember fell through the sealed heavens, he carried it home in his bare hands. The Observatory of the Last Star rose around its light. Now he walks beyond the battle line, gathering its scattered fire into his staff. He does not seek a throne or the worship owed to gods. He keeps a smaller promise: while one light remains, the night will never belong to them. Only one sworn keeper on each side may bear that burden.',effect:'A ranged spellcaster with 210 health and 36-unit casting reach. Train at the Observatory of the Last Star. Living units and training queues share a one-per-side limit; an opposing side may field its own arcanist.',rune:'divine',art});
   statuses.push({id:'starshard',name:'Starshard',kind:'Arcane attack',detail:'36 magic damage · 2.2-second cast cycle',summary:'A splinter of stolen starlight.',effect:'Fires a traveling bolt of starlight at an enemy in clear line of sight.',rune:'divine',art});
   statuses.push({id:'fallingConstellation',name:'Falling Constellation',kind:'Area spell',detail:unit.starfallCooldown>0?`${Math.ceil(unit.starfallCooldown)}s until ready`:'Ready · 64 magic damage in 7 units',summary:'Seven lights fall where his staff points.',effect:'Every 12 seconds, a projectile impact bursts into starlight, dealing 64 magical area damage within 7 units. Requires clear line of sight.',rune:'fury',art});
   statuses.push({id:'eventidePassage',name:'Eventide Passage',kind:'Automatic escape',detail:unit.eventideVeil>0?`${Math.ceil(unit.eventideVeil)}s · beyond the hunt`:unit.eventideCooldown>0?`${Math.ceil(unit.eventideCooldown)}s until ready`:'Ready · escape the hunt',summary:'The hunter closes its jaws upon an empty constellation.',lore:'The last star taught its keeper a secret older than roads: every patch of open sky is a door. When an attacker closes in, his shape breaks into starlight and steps through the night between two stars.',effect:'Automatically teleports when any hostile targets the wizard or comes within 20 units. Lands in a checked open clearing at least 38 units from nearby enemies; breaks pursuit and suspends casting. Untargetable and immune to damage for 6 seconds; 8-second cooldown. Requires a safe landing.',rune:'divine',art});
   statuses.push({id:'distantStar',name:'Distant Star',kind:'Combat positioning',detail:'30-unit standoff · 36-unit casting reach',summary:'Beyond the healers, beyond the reach of claw and thunder.',effect:'Automatically seeks a clear casting position about 30 units from the fight and at least 6 units beyond nearby healers. Retreats before casting if enemies close in. Ground movement orders remain available.',rune:'ward',art});
   statuses.push({id:'astralMantle',name:'Astral Mantle',kind:'Protection',detail:unit.astralMantleTimer>0?`${Math.ceil(unit.astralMantleTimer)}s · 70% less damage`:unit.astralMantleCooldown>0?`${Math.ceil(unit.astralMantleCooldown)}s until ready`:'Ready · guards a lethal approach',summary:'The last star folds its light around its keeper.',effect:'A hit that would take the wizard below 35% health triggers 70% damage reduction for 6 seconds, including that hit. 30-second cooldown. Does not heal or resurrect.',rune:'ward',art});
  }

  if(unit.type==='spearwarden')statuses.push({id:'spearwardenOath',name:'The Promise Between Shields',kind:'Crown Spearwarden',detail:'Keeper of the line',summary:'Trust the shield beside you. Be worthy of its trust.',lore:'At the crossing of the Whitewater, the watch had enough shields for half its number. A young sentry cut ash poles from the riverbank and set his companions between the shieldmen, their spearpoints reaching past the battered rims. Through the longest night of that winter, each guarded the space the next could not. When relief arrived, the crossing still belonged to the living.\n\nThe Spearwardens remember that night in their first lesson. A recruit must learn the breathing of the soldier beside them before learning the killing thrust. They practice giving ground without breaking ranks, finding an opening without crowding a friend, and holding their point steady when fear makes the shaft tremble. Precision is a kindness to those who must trust it.\n\nTheir finest spears bear no tally of the fallen. Beneath the iron socket, a small band of teal cloth remembers the company that first welcomed its bearer into the line. Wherever that cloth is raised, someone has promised to watch the space beside another shield.',effect:'A disciplined melee fighter who strikes with a long spear alongside the frontline.',rune:'ward'});
  if(unit.type==='shieldbearer')statuses.push({id:'shieldbearerOath',name:'The Shield at the Broken Gate',kind:'Crown Shieldbearer',detail:'Sworn guardian',summary:'Behind this shield, another life goes on.',lore:'The first Crown Shieldbearer was not remembered for a victory. When the northern gate fell, he planted a battered shield between the breach and the families still crossing the square. No king stood beside him. No song promised that he would survive. He held because someone had to. By dawn, the square was empty and the inside of his shield bore the names of those he had brought through.\n\nThose who take his oath still write a name beneath the grip: a child, a friend, sometimes a stranger they could not save. They learn to draw danger toward themselves and make room for others to stand. Their armor can buckle. Their hands can shake. Courage, they are taught, is what the frightened do with the next breath.\n\nThe crown upon their shields belongs to the people behind them. Wherever the line breaks, a Shieldbearer steps into the opening, carrying that first soldier’s unfinished watch.',effect:'A frontline guardian who draws enemy attention and protects the company.',rune:'ward'});
  if(lastCrownMercyActive(unit))statuses.push({id:'lastCrownMercy',name:'Mercy of the Last Crown',kind:'Emergency blessing',detail:'Below 10% health · 5× healing received',summary:'While one shield still stands, hope refuses to fall.',lore:'At the edge of the final breath, the sworn shield becomes a beacon. Every Hearthkin prayer finds it, every ember answers, and the company pours its remaining hope into the one who stands before them.',effect:'Multiplies healing received from Hearthkin by five while the tank is below 10% maximum health. Ends as soon as health reaches 10%.',rune:'ward'});
  if(UNIT_TYPES[unit.type]?.magicImmune)statuses.push({id:'beyondFirstOath',name:'Beyond the First Oath',kind:'Innate protection',detail:'Permanent · immune to all harm',summary:'No spell may bind them. No god may claim them.',lore:'No chronicle agrees on where the Hearthkin began. Some say they kindled the first light and shaped the universe around its warmth, long before the old gods learned their names. Others call them visitors from a place beyond the farthest stars, where even time moves by unfamiliar laws. Perhaps both stories are true. Perhaps the world they are said to have made was only one stop on a journey no mortal could imagine.\n\nThey offer no answer. Nearly immortal, they pass through the ages with a quiet familiarity that unsettles kings and comforts children. Ancient powers cannot bind them, and the oldest gods speak carefully in their presence. Those who have glimpsed the radiance beneath their familiar faces remember a flame that seemed less like magic than the memory of creation itself.\n\nWhether they have returned to something they once made, or merely paused beside a distant light, remains unknown. The Hearthkin keep their own counsel. The universe keeps the rest.',effect:'Permanently immune to all damage, hostile magic, curses, and stuns. An attempted damaging hit awakens Last Light Ward without taking health. Friendly healing and blessings still work.',rune:'ward'});
  if(deathlessActive(unit))statuses.push({id:'deathlessHeart',name:'Heart of the Deathless Greatwood',kind:'Last stand · empowered',detail:`${Math.ceil(unit.deathlessTimer)}s · 99% less incoming damage`,summary:'Even death must wait beneath the ancient boughs.',effect:'Triggers below 5% health: takes 99% less damage for 60 seconds. Remains active through healing. After it expires, heal above 60% to ready it again.',rune:'ward',art:bearVariant(unit).art});
  if(unit.type==='grizzly'){
   statuses.push({id:'kingsbaneHunger',name:'Kingsbane Hunger',kind:'Predator’s blessing',detail:'Predator’s blessing',summary:'A faltering shield awakens an ancient hunger.',effect:'Doubles damage dealt to tanks whose health is below 50% when the hit lands. Their defenses still apply.',rune:'fury',art:bearVariant(unit).art});
   statuses.push({id:'falteringCrown',name:'Scent of the Faltering Crown',kind:'Predator’s instinct',detail:'Hunts the weakest nearby tank',summary:'The wild knows which oath is nearest breaking.',effect:'Hunts the targetable tank with the lowest health percentage within 24 units and clear line of sight. Reassesses as health changes.',rune:'fury',art:bearVariant(unit).art});
  }
  if(unit.type==='grizzly')statuses.push({id:'greatwoodDefiance',name:'Defiance of the Greatwood',kind:'Nearby strength',detail:`${unit.greatwoodDefianceStacks??0} nearby · +${Math.round((bearCrowdMultiplier(unit)-1)*100)}% damage and armor`,summary:'The gathering crowd awakens the forest’s defiance.',effect:'Each living worker or fighter within 30 units grants 5% more damage and armor. Bonuses fade as units leave or die. Wildlife does not count.',rune:'fury',art:bearVariant(unit).art});
  if(unit.type==='shieldbearer')statuses.push({id:'crownsAegis',name:'Aegis of the Unbroken Crown',kind:'Permanent AoE protection',detail:'90% less AoE damage',summary:'The sworn shield stands firm when the battlefield erupts.',effect:'Reduces incoming area damage by 90%. Applies alongside the tank’s other defenses.',rune:'ward'});
  if(unit.type==='shieldbearer')statuses.push({id:'oathboundStride',name:'Oathbound Stride',kind:'Permanent blessing',detail:'1.5× fastest base movement',summary:'The sworn shield reaches danger first.',effect:'Base movement speed is 1.5 times the fastest other unit. Terrain and roads still apply.',rune:'ward'});
  if(bearEnrageActive(unit))statuses.push({id:'greatwoodColossus',name:'Greatwood Colossus',kind:'Enrage',detail:'50% true health · double size and damage',summary:'Wounded ancient blood awakens a towering guardian.',effect:'At 50% health, doubles the bear’s size and damage for the rest of its life.',rune:'fury',art:bearVariant(unit).art});
  if(bearEnrageActive(unit)||fury)statuses.push({id:'bloodclawReckoning',name:'Bloodclaw Reckoning',kind:'Area of effect',detail:'8-second cooldown · 50% maximum-health damage',summary:'Three crimson claws tear across the battle line.',effect:'Every 8 seconds, sweeps all enemies within 14 units and clear line of sight for 50% of their maximum health as area damage. Target defenses still apply.',rune:'fury',art:bearVariant(unit).art});
  if(lastBastionActive(unit))statuses.push({id:unit.type==='grizzly'?'unbrokenWild':'crownsLastBastion',name:unit.type==='grizzly'?'Heart of the Unbroken Wild':'The Crown’s Last Bastion',kind:'Last stand · active',detail:`${Math.ceil(unit.lastStandTimer)}s · 90% less incoming damage`,summary:unit.type==='grizzly'?'The ancient wild refuses to yield its heart.':'When the crown has nowhere left to retreat, its shield becomes a fortress.',effect:`Triggers below 20% true health and reduces damage after armor by 90%. Lasts up to ${unit.type==='grizzly'?60:20} seconds, ending early only above 60% health. Crossing damage below 20% is protected. Must heal above 60% to rearm after use.${unit.type==='grizzly'?' Also restores 2% maximum health every 5 seconds while active.':''}`,rune:'ward',art:unit.type==='grizzly'?bearVariant(unit).art:undefined});
  if(elder)statuses.push({id:'crushingClaws',name:'Crushing Claws',kind:'Tank pressure',detail:'6× strike damage against tanks',summary:'Greatwood claws crush a shield line.',effect:'Multiplies ordinary strike damage against tanks by six, before their defenses apply.',rune:'fury',art:bearVariant(unit).art});
  if(elder){
    const bloodline=bearVariant(unit);
    statuses.push({...FIRST_CONDEMNATION,art:bloodline.art,detail:'Permanent · elder magic',rune:'divine'});
    statuses.push({id:'elderhide',name:'Elderhide',kind:'Permanent protection',detail:'95% less projectile and magic damage',summary:'Steel splinters. Sorcery fades. The ancient hide endures.',lore:'The old gods tempered flesh into a living bulwark. Hurled weapons shatter against it, and spellfire dwindles to embers.',effect:'Reduces incoming projectile and magical damage by 95%. Magical projectiles receive this reduction once.',rune:'ward',art:bloodline.art});
    statuses.push({id:'thickHide',name:'Thick Hide',kind:'Permanent armor',detail:'+100% armor · twice the durability',summary:'A second life of punishment beneath the fur.',lore:'The old sentence hardened into hide. Dense guard hairs cover layers of scarred flesh that turn blades and swallow the force of arrows.',effect:'Reduces all incoming damage by 50%.',rune:'ward',art:bloodline.art});
    statuses.push({id:'bearLineage',name:bloodline.name,kind:bloodline.kind,detail:'Greatwood bloodline',summary:bloodline.summary,lore:`${bloodline.lore}\n\n${bloodline.resilience}`,effect:'An ancient Greatwood bloodline, bound to its ancestral watch.',rune:'divine',art:bloodline.art});
  }
  if(unit.lastLightChorusTimer>0)statuses.push({id:'lastLightChorus',name:'Chorus of the Last Light',kind:'Team blessing',detail:`${Math.ceil(unit.lastLightChorusTimer)}s · 200% healing received`,summary:'One life spared becomes hope for the whole company.',lore:'When the Hearthkin’s shield kindles, its light passes from companion to companion. The old prayer asks no price of an enemy; it binds the living together until their strength returns.',effect:'Doubles healing received for 60 seconds. A new application refreshes the duration without stacking.',rune:'ward'});
  if(unit.lastLightWardTimer>0)statuses.push({id:'ward',name:'Last Light Ward',kind:'Protection',detail:`${Math.ceil(unit.lastLightWardTimer)}s · invulnerable`,summary:'No blade may reach them. No power may lay claim.',lore:'When harm reaches for them, the first flame gathers its children beyond its grasp. Steel passes without purchase. Sorcery finds nothing to bind. Even the wrath of the old gods breaks against that quiet light. While the ward endures, the Hearthkin are untouchable.',effect:'Awakens when an attack attempts to deal damage. No health is lost. For 60 seconds, the revealed ward prevents attack targeting and shares healing light with the team.',rune:'ward'});
  if(fury)statuses.push({id:'greatwoodFury',name:'Wrath of the First Oath',kind:'Fury · active',detail:'6× damage · frontal swipe',summary:'The ancient sentence answers the scent of death.',lore:'As a Greatwood bear’s strength falls to its last tenth, the first oath tightens. The condemned blood remembers the ruin of the star-grove. A final measure of the old gods’ wrath passes into every claw.',effect:'At 10% health or below, multiplies damage by six. Landed strikes are lethal to non-tank fighters. Ordinary strikes require frontal contact and clear line of sight.',rune:'fury',art:bearVariant(unit).art});
  if(unit.stunTimer>0)statuses.push({id:'stun',name:'Stunned',kind:'Impairment',detail:`${Math.ceil(unit.stunTimer)}s remaining`,summary:'Movement and attacks are interrupted.',rune:'stun'});
  if(unit.stunImmunityTimer>0)statuses.push({id:'stunImmunity',name:'Steadfast',kind:'Protection',detail:`${Math.ceil(unit.stunImmunityTimer)}s · stun immunity`,summary:'Cannot be stunned while this protection lasts.',rune:'ward'});
  return statuses;
}

// One authored thorned glyph shared by Canvas markers and the inspection UI.
// Open barbs and a broken crown replace the old diamond and pulsing circle.
export const SIGIL_STROKES=[[[0,-14],[0,13],[-3,17]], [[-10,-13],[-7,-6],[0,-10],[7,-6],[10,-13]], [[-12,-3],[-7,3],[0,-1],[7,3],[12,-3]], [[-8,8],[0,5],[8,8]], [[-5,13],[0,10],[5,13]]];
export const SIGIL_COLORS={divine:'#cd8656',curse:'#bd8ec9',ward:'#d6c995',stun:'#c99b67'};
export function sigilSvg(kind='curse'){
  if(kind==='fury')return '<svg viewBox="-19 -20 38 42" aria-hidden="true" fill="none" stroke="#e98b56" stroke-width="2.6"><path d="M-10-15Q-15 0-9 15L-3 8 M0-17Q-5 0 1 17L7 9 M10-14Q5 0 11 14L16 7"/></svg>';
  if(kind==='ward')return '<svg viewBox="-19 -20 38 42" aria-hidden="true" fill="none" stroke="#d6c995" stroke-width="2"><path d="M-12-12Q0-18 12-12L10 3Q7 11 0 16Q-7 11-10 3Z M0-10V9 M-6-3L0-7 6-3 M-5 3L0-1 5 3"/></svg>';
  if(kind==='stun')return '<svg viewBox="-19 -20 38 42" aria-hidden="true" fill="none" stroke="#c99b67" stroke-width="2"><path d="M2-15L-7 1H0L-2 16 9-3H2Z M-14-8L-10-6 M10 10L14 12"/></svg>';
  const paths=SIGIL_STROKES.map(points=>`<polyline points="${points.map(p=>p.join(',')).join(' ')}"/>`).join('');
  return `<svg viewBox="-19 -20 38 42" aria-hidden="true" fill="none" stroke="${SIGIL_COLORS[kind]??SIGIL_COLORS.curse}" stroke-width="2.2" stroke-linejoin="miter">${paths}</svg>`;
}
export function curseRuneKind(unit){return isCurseImmune(unit)?'divine':null;}
export function drawCurseSigil(ctx,kind,x,y,size){
  ctx.save();ctx.translate(x,y);ctx.scale(size/38,size/38);ctx.lineCap='square';ctx.lineJoin='miter';
  for(const [color,width] of [['#231a1b',5],[SIGIL_COLORS[kind]??SIGIL_COLORS.curse,2.2]]){
    ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();
    for(const points of SIGIL_STROKES){ctx.moveTo(...points[0]);for(const p of points.slice(1))ctx.lineTo(...p);}
    ctx.stroke();
  }
  ctx.restore();
}
