import {HEARTHKIN_ART} from './painted-art.js';
import {WORK_ART} from './work-art.js?v=study2';
import {ACTIONS} from './action-catalog.js';
import {BEAR_REFERENCE} from './bear-reference.js';
import {VIEWS,frameIndex,directionFor,advanceActor} from './motion.js';
import {drawWard,drawRune,drawRelease} from './effects-v2.js';
const $=id=>document.getElementById(id),canvas=$('stage'),ctx=canvas.getContext('2d');
const controls=Object.fromEntries(['action','view','speed','size','all-views','travel','guides','ghost','shield','curse','repeat'].map(id=>[id,$(id)]));
const art=Object.fromEntries(Object.keys(VIEWS).map(v=>[v,{...HEARTHKIN_ART[v],...WORK_ART[v]}]));
for(const [id,def] of Object.entries(ACTIONS))if(def.source)for(const view of Object.keys(VIEWS)){const source=art[view][def.source];if(source)art[view][id]={...source,frames:def.indices.map(i=>source.frames[i])};}
const available=Object.keys(ACTIONS).filter(a=>Object.values(art).every(v=>v[a]));
const groups=new Map();for(const key of available){const d=ACTIONS[key];if(!groups.has(d.group)){const group=document.createElement('optgroup');group.label=d.group;groups.set(d.group,group);controls.action.append(group);}const o=document.createElement('option');o.value=key;o.textContent=d.label;groups.get(d.group).append(o);}
const params=new URLSearchParams(location.search);controls.action.value=available.includes(params.get('action'))?params.get('action'):available.includes('gather_wood')?'gather_wood':'walk';controls.view.value=VIEWS[params.get('view')]?params.get('view'):'sw';
const cache=new Map(),images={},errors=[],actor={x:0,y:0,target:{x:.65,y:.2}},points=[{x:.65,y:.2},{x:-.55,y:.65},{x:-.6,y:-.25},{x:.55,y:-.5}];
let phase=0,paused=false,ready=false,last=0,stripKey='',highlight=-1,rendered=0,route=0,manual=false,request=0,loadedAction='',lastStatus=0,touring=false,tourTime=0;
const reviewed=new Set();
const oneShot=()=>ACTIONS[controls.action.value].loop===false;
const canTravel=()=>controls.action.value==='walk'||controls.action.value.startsWith('carry_');
const sheet=(view=controls.view.value)=>art[view][controls.action.value];
const index=()=>frameIndex(phase,sheet().frames.length);
function setPaused(value){paused=value;$('play').textContent=value?(oneShot()&&phase>.99?'Replay':'Play'):'Pause';$('play').setAttribute('aria-pressed',String(!value));}
function advancePhase(seconds){const next=phase+seconds/ACTIONS[controls.action.value].seconds;if(next>=1&&oneShot()&&!controls.repeat.checked){phase=.999999;setPaused(true);}else phase=next%1;}
function step(delta){setPaused(true);const n=sheet().frames.length;phase=((index()+delta+n)%n+.001)/n;}
$('play').onclick=()=>{if(paused&&phase>.99&&oneShot())phase=0;setPaused(!paused);};$('previous').onclick=()=>step(-1);$('next').onclick=()=>step(1);
$('timeline').oninput=e=>{phase=Number(e.target.value)/1000;setPaused(true);};
$('reset').onclick=()=>{actor.x=actor.y=0;actor.target={...points[0]};route=0;manual=false;phase=0;setPaused(false);};
async function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('Cannot load '+src));image.src=src;});}
async function loadAction(){const id=controls.action.value,token=++request;ready=false;stripKey='';$('health').textContent='Loading '+ACTIONS[id].label+'…';try{const sets=Object.values(art).map(v=>v[id]),unique=[...new Set(sets.map(s=>s.src))],loaded=await Promise.all(unique.map(async src=>[src,await loadImage(src)]));if(token!==request)return;cache.clear();const map=Object.fromEntries(loaded);for(const s of sets)cache.set(s,s.frames.map(f=>{const c=document.createElement('canvas');c.width=f.rect[2];c.height=f.rect[3];const g=c.getContext('2d');if(f.clip){g.beginPath();for(const r of f.clip)g.rect(...r);g.clip();}g.drawImage(map[s.src],...f.rect,0,0,c.width,c.height);return c;}));ready=true;loadedAction=id;reviewed.add(id);phase=0;tourTime=0;setPaused(false);}catch(e){if(token!==request)return;errors.push(String(e));$('health').textContent=String(e);}}
for(const [id,input] of Object.entries(controls))input.addEventListener('input',()=>{
 if(id==='action'){touring=false;$('tour').textContent='Preview every action';if(!canTravel())controls.travel.checked=false;actor.x=actor.y=0;loadAction();}
 if(id==='view'){stripKey='';if(controls.travel.checked){const [x,y]=VIEWS[input.value].vector;actor.target={x:x*.6,y:y*.7};manual=true;}}
 if(id==='all-views'&&input.checked)controls.travel.checked=false;
 if(id==='travel'&&input.checked){controls['all-views'].checked=false;manual=false;if(!canTravel()){controls.action.value='walk';loadAction();}setPaused(false);}
 if(id==='speed')$('speed-label').textContent=Number(input.value)+'×';
 if(id==='size')$('size-label').textContent=input.value+' px';
});
$('tour').onclick=()=>{touring=!touring;$('tour').textContent=touring?'Stop action tour':'Preview every action';tourTime=0;controls.travel.checked=false;if(touring){controls.action.value=available[0];loadAction();}};
canvas.onclick=e=>{if(!controls.travel.checked||!canTravel())return;const r=canvas.getBoundingClientRect();actor.target={x:Math.max(-.8,Math.min(.8,(e.clientX-r.left-r.width*.5)/(r.width*.25))),y:Math.max(-.7,Math.min(.7,(e.clientY-r.top-r.height*.84)/(r.height*.12)))};manual=true;setPaused(false);};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON','SUMMARY'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();$('play').click();}if(e.key==='ArrowRight'){e.preventDefault();step(1);}if(e.key==='ArrowLeft'){e.preventDefault();step(-1);}});
window.addEventListener('error',e=>errors.push(e.message));window.addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
function drawPainting(g,view,p,x,y,size,alpha=1){const s=sheet(view),i=frameIndex(p,s.frames.length),f=s.frames[i],im=cache.get(s)?.[i];if(!im)return;const k=size/s.scaleBase;g.save();g.globalAlpha*=alpha;g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(im,x-f.pivot[0]*k,y-f.pivot[1]*k,f.rect[2]*k,f.rect[3]*k);g.restore();}
function bear(g,x,y,height){if(!images.bear)return;const f=BEAR_REFERENCE.frames[0],k=height/BEAR_REFERENCE.scaleBase;g.save();g.translate(x-f.pivot[0]*k,y-f.pivot[1]*k);g.scale(k,k);if(f.clip){g.beginPath();for(const r of f.clip)g.rect(...r);g.clip();}g.drawImage(images.bear,...f.rect,0,0,f.rect[2],f.rect[3]);g.restore();}
function ground(w,h){ctx.fillStyle='#3e5539';ctx.fillRect(0,0,w,h);if(images.grass){for(let y=0;y<h;y+=320)for(let x=0;x<w;x+=320)ctx.drawImage(images.grass,x,y,320,320);ctx.fillStyle='#152d2160';ctx.fillRect(0,0,w,h);}const grad=ctx.createRadialGradient(w*.5,h*.4,0,w*.5,h*.5,w*.7);grad.addColorStop(0,'#18291c00');grad.addColorStop(1,'#11231999');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);}
function panel(view,left,top,w,h,all){const action=controls.action.value,release=action==='last_light'&&!all,leftward=view==='sw'||view==='nw',size=Math.min(Number(controls.size.value),h*(all?.66:.65),w*(release?.4:.5)),x=left+w*(release?(leftward?.68:.32):.5)+(controls.travel.checked?actor.x*w*.25:0),y=top+h*.84+(controls.travel.checked?actor.y*h*.12:0);ctx.save();ctx.beginPath();ctx.rect(left,top,w,h);ctx.clip();const ward=controls.shield.checked||['ward_raise','ward_block','last_light'].includes(action);if(ward)drawWard(ctx,x,y,size,phase,true,action==='ward_block',action==='ward_raise');ctx.fillStyle='#07160f38';ctx.beginPath();ctx.ellipse(x,y+2,size*.17,size*.03,0,0,Math.PI*2);ctx.fill();if(controls.guides.checked){ctx.strokeStyle='#ddc99aa0';ctx.setLineDash([4,5]);ctx.beginPath();ctx.moveTo(x-size*.3,y);ctx.lineTo(x+size*.3,y);ctx.moveTo(x,y-size);ctx.lineTo(x,y+10);ctx.stroke();ctx.setLineDash([]);}if(controls.ghost.checked)drawPainting(ctx,view,phase-1/sheet().frames.length,x,y,size,.2);drawPainting(ctx,view,phase,x,y,size);if(ward)drawWard(ctx,x,y,size,phase,false,action==='ward_block',action==='ward_raise');if(controls.curse.checked||action==='last_light_cursed')drawRune(ctx,x,y-size*1.09,size*.12);
 if(release){const bx=left+w*(leftward?.21:.79);bear(ctx,bx,y,size*.93);drawRelease(ctx,x,y,bx,y,size,phase);if(phase>.55){drawRune(ctx,bx,y-size*1.02,size*.13);ctx.font='11px system-ui';ctx.textAlign='center';ctx.fillStyle='#ead2eb';ctx.fillText('Last Light · apparent 1 HP',bx,y+22);}}
 if(all){ctx.font='11px system-ui';ctx.textAlign='center';ctx.fillStyle='#f0e5c6';ctx.fillText(VIEWS[view].label,left+w*.5,top+h-8);}ctx.restore();}
function updateStrip(){const s=sheet(),key=controls.view.value+'/'+controls.action.value;if(key!==stripKey){stripKey=key;$('frames').replaceChildren();s.frames.forEach((f,i)=>{const b=document.createElement('button');b.className='frame';b.setAttribute('aria-label','Hold painting '+(i+1));const c=document.createElement('canvas');c.width=c.height=240;b.append(c);const label=document.createElement('span');label.textContent=String(i+1).padStart(2,'0')+' / '+s.frames.length;b.append(label);drawPainting(c.getContext('2d'),controls.view.value,(i+.001)/s.frames.length,120,221,180);b.onclick=()=>{phase=(i+.001)/s.frames.length;setPaused(true);};$('frames').append(b);});highlight=-1;}const i=index();if(i!==highlight){[...$('frames').children].forEach((b,j)=>{b.classList.toggle('active',i===j);b.setAttribute('aria-pressed',String(i===j));});highlight=i;}$('view-label').textContent=controls['all-views'].checked?'Four painted views':VIEWS[controls.view.value].label;$('frame-label').textContent=ACTIONS[controls.action.value].label+' · '+(i+1)+' / '+s.frames.length;$('pose-note').textContent=ACTIONS[controls.action.value].labels[i]??'';$('position').textContent=Math.floor(phase*100)+'%';$('timeline').value=Math.floor(phase*1000);$('hint').textContent=controls.travel.checked?'Click the clearing to set a destination.':oneShot()?'Plays once and holds. Use Replay to repeat.':'A repeating work cycle.';}
function drawScale(){const c=$('scale'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);drawPainting(g,'sw',phase,58,218,100);bear(g,215,218,185);}
function tick(now){const dt=Math.min(.05,(now-(last||now))/1000);last=now;if(ready&&!paused){const elapsed=dt*Number(controls.speed.value);if(controls.travel.checked&&canTravel()){const dx=actor.target.x-actor.x,dy=actor.target.y-actor.y,moved=advanceActor(actor,elapsed);if(moved){controls.view.value=directionFor(dx,dy);advancePhase(elapsed);}else if(!manual){route=(route+1)%points.length;actor.target={...points[route]};}else{phase=0;setPaused(true);}}else advancePhase(elapsed);}
 if(ready&&touring){tourTime+=dt;if(tourTime>Math.max(1,ACTIONS[controls.action.value].seconds)+.5){const next=available.indexOf(controls.action.value)+1;if(next<available.length){controls.action.value=available[next];loadAction();}else{touring=false;$('tour').textContent='Preview every action';}}}
 const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(2,devicePixelRatio||1);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ground(w,h);if(ready){if(controls['all-views'].checked)['sw','se','nw','ne'].forEach((v,i)=>panel(v,(i%2)*w/2,Math.floor(i/2)*h/2,w/2,h/2,true));else panel(controls.view.value,0,0,w,h,false);updateStrip();drawScale();}else{ctx.fillStyle='#eadfc2';ctx.textAlign='center';ctx.font='16px Georgia';ctx.fillText('Preparing '+ACTIONS[controls.action.value].label.toLowerCase()+'…',w/2,h/2);}
 rendered++;if(now-lastStatus>500){lastStatus=now;const count=Object.values(art.sw).reduce((n,s)=>n+s.frames.length,0)*4;window.hearthkinStudio={ready,action:controls.action.value,loadedAction,view:controls.view.value,phase,paused,rendered,errors,available,reviewed:[...reviewed],touring,cachePaintings:[...cache.values()].reduce((n,a)=>n+a.length,0)};if(ready)$('health').textContent=`${available.length} actions · ${reviewed.size} opened · 4 views · ${count} frame entries · ${rendered} rendered · ${errors.length} errors`;}requestAnimationFrame(tick);}
try{[images.grass,images.bear]=await Promise.all([loadImage('./assets/grass.png'),loadImage('./assets/bear-reference.png')]);await loadAction();requestAnimationFrame(tick);}catch(e){errors.push(String(e));$('health').textContent=String(e);}
