// Existing IDs 0–2 are retained so older saves keep their discoveries.
export const MEMORIES = [
 {id:0,chapter:1,x:975,y:390,title:'The light entrusted',place:'The Silverwood · the keeper’s oath',art:'memory-1-grounded-v2.png',alt:'An elderly keeper entrusts a living star ember to the silver-haired wizard beneath a brass astrolabe.',paragraphs:[
 'I was not the first to carry the last star. When the old gods sealed the night, an earlier arcanist caught the ember that escaped and carried it to a ruined watchtower. Stone by stone, that refuge became our Observatory. I inherited its keys long after the hands that laid those stones were dust.',
 'My teacher placed the ember between my palms. It gave no heat. Instead I heard rain on the roof, someone sweeping the stair, a bird waking beyond the shutters. All the small things I had stopped listening to while learning to command the heavens.',
 '“You are its keeper,” my teacher told me. “That is different from being its owner.” I repeated the oath without understanding it. The star was so small. I thought keeping it safe would be enough.' ]},
 {id:1,chapter:3,x:3125,y:420,title:'The measure of a sky',place:'The aqueduct · before the silence',art:'memory-3.png',alt:'The wizard and an elderly astronomer study a blue ember suspended inside the Observatory’s brass instrument.',paragraphs:[
 'After Bracken Ford, the road lamps seemed unbearably few. I returned to the Observatory carrying a grand answer: if one ember could guide a bridge, perhaps its light could reach every road. The astronomer who tended our instruments listened without interrupting.',
 'Together we set seven brass rings around the living star. He measured what the apparatus could hold. I kept asking what more it could give. When the innermost ring began to sing, he laid a hand on mine. “A light is not made kinder by being made to burn without rest.”',
 'I turned the ring anyway. For one heartbeat, every window shone like dawn. Then the shadows inside the chamber moved toward the star. I had mistaken brightness for care—and opened a way for the dark to follow it home.' ]},
 {id:2,chapter:5,x:5520,y:430,title:'What the storm remembers',place:'The high ruins · Vaelthryx',art:'memory-5.png',alt:'The silver-haired wizard raises his star staff toward a vast blue dragon among moonlit storm clouds.',paragraphs:[
 'I climbed above the ruined aqueduct because the wind was louder there than my thoughts. Lightning unfolded across the clouds. In its white branches I saw Vaelthryx, vast enough to make the mountains seem like broken teeth.',
 'I raised my staff as though a spell could summon an answer from him. The dragon lowered his head, and the ember answered first. Its pulse traveled through the brass into my hands. Not a command. Recognition. He remembered the light from before it had a keeper.',
 'For the first time since the chamber fell silent, I lowered the staff. I asked for help. When the thunder came, I could hear a path through it. Vaelthryx would answer the star—but I would still have to walk back to the door I had abandoned.' ]},
 {id:3,chapter:2,x:1900,y:470,title:'The lamps of Bracken Ford',place:'The river crossing · a lesson in keeping',art:'memory-2.png',alt:'The wizard lights a stone bridge for villagers and Crownwardens crossing above a dark river.',paragraphs:[
 'The Crownwardens found me at Bracken Ford with a cart of star charts and no idea how to mend a bridge. The flooded road vanished beneath the water at the bridge’s approach. Families waited on the bank, clutching blankets, bread, a cage with nothing left inside it.',
 'One warden handed me a lantern. “Can your star show us where to put our feet?” So I held its light over the crossing while they led each family onto the stones. They carried the children first. The royal gold could wait. A little girl counted each person who reached the far bank; when she lost count, she began again.',
 'Near morning she returned the lantern, though I had forgotten it was mine. “You kept it on,” she said. No one asked how powerful the star was. They had needed a light that stayed.' ]},
 {id:4,chapter:4,x:4670,y:430,title:'The door I left behind',place:'The broken aqueduct · the night of the breach',art:'memory-4.png',alt:'The exhausted wizard shelters the star ember in the rain beneath broken aqueduct arches, with the dark Observatory behind him.',paragraphs:[
 'The astronomer pushed the ember into my staff and sent me toward the stair. He remained at the great astrolabe, holding its rings apart while the darkness pressed between them. I promised I would come back with help. The door shut before he could answer.',
 'I reached the aqueduct with his voice still in my ears. Rain gathered in the broken places of my staff. Across the valley, one Observatory window went dark, then another. I knelt beneath an arch and held the ember so tightly that its brass setting cut my palm.',
 'For a long time I called that night an escape. It was easier than calling it what followed: a choice to keep walking away. The star survived. My promise remained on the other side of the door.' ]},
 {id:5,chapter:6,x:6725,y:570,title:'A keeper returns',place:'The Observatory threshold · now',art:'memory-6.png',alt:'At the Observatory entrance the wizard offers the ember toward a hollow spectral astronomer beneath an unlit astrolabe.',paragraphs:[
 'Here is the door. Smaller than it has been in my dreams. Beyond it, the astronomer still circles his instrument, guarding a sky that no longer exists. The thing the darkness has made of him cannot hear an apology. Perhaps some part of him can still recognize the light.',
 'I cannot undo the turn of that brass ring. I cannot promise that returning the ember will give back everything it took. I can stop asking the star to make me powerful enough to escape what I have done.',
 'I open my hand. After the guardian is freed, I will carry the ember to its resting place, and we will see which lamps can be lit again. I am the keeper of the last star. This time, I mean to stay.' ]},
];
