import { BUILDING_TYPES } from '../src/config.js?v=20260921-autogroup1';
import { CROWN_ARCHITECTURE } from '../src/architecture-data.js?v=20260921-autogroup1';
const {simulation:s,renderer:r}=window.crownforge;
s.units=[];s.pausedEnemyUnits=[];s.buildings=[];s.resourcesNodes=[];s.decorations=[];s.projectiles=[];s.navigationVersion++;
s._checkVictory=()=>{};s._updateEnemyAI=()=>{};s._updateEnemyIntent=()=>{};s._updateMilitaryServices=()=>{};s._updateWorkerServices=()=>{};s.wildlifeState.nextSpawnAt=Infinity;
s._updateUnit=(u,dt)=>{u.animClock=(u.animClock??0)+dt;};
let current;
function focus(detail=false){const b=current,size=r.buildingRenderSize(b),height=r.buildingVisualHeight(b,size);r.camera.zoom=detail?1:Math.min(1.5,(r.width-140)/size,(r.height-250)/(height+100));r.zoomMotion=null;r.cameraInitialized=true;const p=r.worldToScreen(b);r.camera.x+=r.width*.5-p.x;r.camera.y+=r.height*.79-p.y;r.invalidateStaticLayer();}
function show(type){s.buildings=[];s.units=[];s.navigationVersion++;current=s.addBuilding(type,220,220,'player',1);for(const [i,t] of ['villager','shieldbearer','militia'].entries())s.addUnit(t,224+i*2,224-i*2,'player');panel.querySelector('select').value=type;panel.querySelector('h1').textContent=BUILDING_TYPES[type].label;focus();}
const style=document.createElement('style');style.textContent='.game-shell>:not(#game-canvas):not(#loading-veil),#unit-activity,#combat-frames{display:none!important}.architecture-gallery{position:fixed;inset:0;pointer-events:none;z-index:80;color:#f4e6c8;text-align:center;background:linear-gradient(#102325ed,transparent 23%,transparent 80%,#102325ed)}.architecture-gallery header{padding:16px}.architecture-gallery h1{font:30px Marcellus,serif;margin:8px}.architecture-gallery footer{position:absolute;bottom:20px;width:100%}.architecture-gallery select,.architecture-gallery button{pointer-events:auto;background:#173538;color:#f4e6c8;border:1px solid #bba268;border-radius:6px;padding:10px 16px;margin:5px;font:14px system-ui}';document.head.append(style);
const panel=document.createElement('section');panel.className='architecture-gallery';panel.innerHTML='<header><p>THE CROWNWARDEN BUILDING COLLECTION</p><h1></h1><select aria-label="Building">'+[...Object.keys(CROWN_ARCHITECTURE),'wall','gate','road','observatory'].map(t=>'<option value="'+t+'">'+BUILDING_TYPES[t].label+'</option>').join('')+'</select></header><footer><button data-fit>Fit building</button><button data-detail>Inspect detail</button><p>Full-resolution paintings · actual game scale · scroll to zoom</p></footer>';document.body.append(panel);
panel.querySelector('select').onchange=e=>show(e.target.value);panel.querySelector('[data-fit]').onclick=()=>focus();panel.querySelector('[data-detail]').onclick=()=>focus(true);show(new URLSearchParams(location.search).get('building')||'homestead');window.architectureGallery={show,focus};
