// Local training scene uses the real controls and combat; no production world changes.
const {simulation:s,renderer:r,audio}=window.crownforge;
s.units=[];s.buildings=[];s.resourcesNodes=[];s.decorations=[];s.projectiles=[];s.navigationVersion++;
s._checkVictory=()=>{};s._updateEnemyAI=()=>{};s._updateEnemyIntent=()=>{};s._updateMilitaryServices=()=>{};s.wildlifeState.nextSpawnAt=Infinity;
const tank=s.addUnit('shieldbearer',172,180,'player'),spear=s.addUnit('spearwarden',168,182,'player'),spear2=s.addUnit('spearwarden',167,184,'player'),healer=s.addUnit('villager',170,178,'player'),bear=s.addUnit('grizzly',184,180,'wildlife');
let running=false,hits=0,protectedHits=0,tankDamage=0;const applyDamage=s._applyUnitDamage.bind(s);s._applyUnitDamage=(target,amount,attacker,...rest)=>{if(attacker===bear){if(target===tank)hits++;else if(!tank.dead)protectedHits++;}const result=applyDamage(target,amount,attacker,...rest);if(target===tank&&attacker===bear)tankDamage+=result.damage;return result;};
const updateUnit=s._updateUnit.bind(s);s._updateUnit=(u,dt)=>{if(running){updateUnit(u,dt);if(tank.dead)running=false;}};
bear.maxHp=18000;bear.hp=18000; // Extended-life training target, visibly labeled.
const pick=units=>{s.selectedIds=units.map(u=>u.id);s._syncSelectionFlags();};pick([tank,spear,spear2,healer]);s.assignSelectedTeam();pick([bear]);
r.camera.zoom=.44;r.zoomMotion=null;r.cameraInitialized=true;const center=r.worldToScreen({x:180,z:180});r.camera.x+=r.width*.62-center.x;r.camera.y+=r.height*.58-center.y;
const bar=document.createElement('section');bar.style='position:fixed;right:12px;bottom:100px;max-width:460px;z-index:8;background:#16271ef2;color:#f4e8c8;padding:12px;border:1px solid #a88c54;border-radius:8px;font:12px system-ui';
bar.innerHTML='<b>Bloodclaw and battle music · local review</b><p>Training bear has extended health. Start combat to hear the battle track, then enrage for Bloodclaw. Defeat the bear to hear the soundtrack fade back.</p><div style="display:flex;gap:5px;flex-wrap:wrap"><button data-pick="spear">Inspect Spearwarden</button><button data-pick="tank">Inspect tank</button><button data-pick="squad">Select squad</button><button data-pick="healer">Inspect Hearthkin</button><button data-bear>Inspect bear</button><button data-enrage>Trigger half-health enrage</button><button data-pause>Pause / resume</button><button data-start>Start training fight</button><button data-swipe>Preview Bloodclaw</button><button data-end>Defeat training bear</button><button data-reset>Reset training</button></div><p data-state></p>';
bar.innerHTML='<details open><summary style="cursor:pointer">Review controls — expand / collapse</summary>'+bar.innerHTML+'</details>';
document.body.append(bar);bar.querySelector('[data-pick=spear]').onclick=()=>pick([tank,spear,spear2,healer]);s.assignSelectedTeam();pick([bear]);bar.querySelector('[data-pick=tank]').onclick=()=>pick([tank]);bar.querySelector('[data-pick=healer]').onclick=()=>pick([healer]);bar.querySelector('[data-pick=squad]').onclick=()=>pick([tank,spear,spear2,healer]);
bar.querySelector('[data-start]').onclick=()=>{audio.unlock();running=true;bear.stunTimer=0;bear.command='idle';tank.hp=tank.maxHp;tank.dead=false;for(const u of [tank,spear,spear2])s._sendUnitToAttack(u,bear);};
bar.querySelector('[data-bear]').onclick=()=>pick([bear]);
bar.querySelector('[data-enrage]').onclick=()=>{bear.hp=bear.maxHp*.5;bear.greatwoodEnraged=true;pick([bear]);};
bar.querySelector('[data-pause]').onclick=()=>{running=!running;};
bar.querySelector('[data-swipe]').onclick=()=>{bear.specialSwipeReadyAt=0;s._applyGrizzlyCleave(bear,tank);bear.animClock+=.25;running=false;bar.querySelector('details').open=false;};
bar.querySelector('[data-end]').onclick=()=>{s._killUnit(bear,tank);};
bar.querySelector('[data-reset]').onclick=()=>location.reload();
setInterval(()=>{bar.querySelector('[data-state]').textContent=`Tank ${Math.ceil(tank.hp)}/${tank.maxHp} HP · Bear target: ${s._getExplicitAttackTarget(bear)?.type??'none'} · Bear HP: ${Math.ceil(bear.hp)} · Size: ${bear.greatwoodEnraged||bear.hp<=bear.maxHp*.5?"2×":"1×"} · Healer distance: ${Math.hypot(healer.x-bear.x,healer.z-bear.z).toFixed(1)} · Heals: ${healer.healTargetId?'active':'waiting'} · Music: ${audio.currentTrack.title} · Loop: ${audio.combat.buffer?audio.combat.buffer.duration.toFixed(2)+"s decoded":audio.combat.status} · Tank hits: ${hits} · Tank damage taken: ${Math.round(tankDamage)} · Rear hits: ${protectedHits}`;},250);
