import test from 'node:test';import assert from 'node:assert/strict';import {Game} from '../src/game.js';import {SelectionRing,grantItem} from '../src/inventory.js';
test('ring releases to equip, never casts, cancellation requires a fresh hold',()=>{const g=new Game(),r=new SelectionRing();r.step({ring:true},g.inventory);r.step({ring:true,interact:true,use:true},g.inventory);assert.equal(r.index,1);assert.equal(r.step({ring:false,use:true},g.inventory).use,false);assert.equal(g.inventory.equipped,'frost');assert.equal(r.step({use:true},g.inventory).use,true);r.step({ring:true},g.inventory);r.cancel();r.step({ring:true},g.inventory);assert.equal(r.open,false);r.step({},g.inventory);r.step({ring:true},g.inventory);assert.equal(r.open,true);});
test('first and last charges, empty use and overflow are transactional',()=>{const g=new Game();assert.equal(g.useItem(),false);grantItem(g,'ember',8);assert.equal(g.inventory.charges.ember,6);assert.equal(g.arcade.score,150);assert.equal(g.useItem(),true);assert.equal(g.inventory.charges.ember,5);assert.equal(g.useItem(),false);assert.equal(g.inventory.charges.ember,5);g.inventory.charges.ember=1;g.inventory.cooldown=0;g.useItem();assert.equal(g.inventory.charges.ember,0);assert.equal(g.inventory.equipped,'ember');});
test('introductory collectible is reachable and collected exactly once',()=>{const g=new Game();const d=g.loot.find(d=>d.kind==='ember');g.player.x=d.x;g.player.y=d.floor+22;for(let i=0;i<60;i++)g.update(1/60);assert.equal(g.inventory.charges.ember,3);assert.ok(!g.loot.includes(d));});
test('flask preserves full-health charge, restores injured health, and cannot overheal',()=>{const g=new Game();grantItem(g,'flask');g.inventory.equipped='flask';assert.equal(g.useItem(),false);assert.equal(g.inventory.charges.flask,1);g.player.hp=190;assert.equal(g.useItem(),true);assert.equal(g.player.hp,210);assert.equal(g.inventory.charges.flask,0);});
test('chain visits at most four distinct targets and invalid casts retain charge',()=>{const g=new Game();grantItem(g,'chain',2);g.inventory.equipped='chain';g.player.x=10;g.enemies.forEach(e=>e.x=2000);assert.equal(g.useItem(),false);assert.equal(g.inventory.charges.chain,2);g.enemies.slice(0,5).forEach((e,i)=>{e.x=200+i*60;e.y=580;e.hp=1000;});assert.equal(g.useItem(),true);assert.equal(g.events.filter(e=>e.type==='chain-arc').length,4);assert.equal(g.enemies.slice(0,5).filter(e=>e.hp<1000).length,4);});
test('freeze shatters once, resists re-freeze; guardian only slows; burns expire',()=>{const g=new Game(),e=g.enemies.find(e=>e.role==='ranged'),attack={bonus:0,used:false};e.hp=1000;g.applyStatus(e,'frost',attack);assert.ok(e.freeze>0);g.damage(e,1,attack);assert.ok(e.freeze>0);g.damage(e,1,{bonus:0});assert.equal(e.freeze,0);g.applyStatus(e,'frost');assert.equal(e.freeze,0);const boss=g.enemies.find(e=>e.type==='boss');g.applyStatus(boss,'frost');assert.ok(boss.slow>0);assert.ok(!boss.freeze);g.applyStatus(e,'ember');for(let i=0;i<240;i++)g.update(1/60);assert.equal(e.burn,0);});
test('three staff levels visibly change projectile strength and count; one Reprisal budget',()=>{for(const [crystals,count,damage] of [[0,1,36],[6,1,46],[15,3,38]]){const g=new Game();g.arcade.crystals=crystals;g.player.retaliation=10;g.spell('bolt');assert.equal(g.projectiles.length,count);assert.equal(g.projectiles[0].damage,damage);assert.equal(new Set(g.projectiles.map(p=>p.attack)).size,1);}});

test("chain stagger is applied before basic hit resistance",()=>{const g=new Game();g.enemies=g.enemies.filter(e=>e.role==='ranged').slice(0,1);const e=g.enemies[0];g.player.x=e.x-200;g.player.y=e.y;grantItem(g,'chain');g.inventory.equipped='chain';g.useItem();assert.equal(e.stagger,.3);assert.equal(e.staggerCd,1.2);});

test('special projectile follows reversed aim from the correct staff side',()=>{const g=new Game();g.player.x=1300;g.player.face=1;grantItem(g,'ember');g.useItem({aimX:1000,aimY:500});assert.equal(g.player.face,-1);assert.ok(g.projectiles[0].x<g.player.x);assert.ok(g.projectiles[0].vx<0);});
